{% set version = load_setup_py_data().version %}

package:
    name: mss
    version: {{ version }}

source:
    git_url: https://bitbucket.org/wxmetvis/mss.git

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt
    skip: True  # [py3k]
    entry_points:
      - mss = mslib.msui.mss_pyui:main
      - mswms = mslib.mswms.mswms:main
      - demodata = mslib.mswms.demodata:main

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - basemap 1.0.7
        - chameleon
        - execnet
        - lxml
        - netcdf4
        - hdf4 4.2.12
        - paste
        - pillow
        - python-dateutil
        - pytz
        - pyqt
        - qt
        - requests
        - scipy
        - six
        - tk 8.5.*
        - pykml

test:
    imports:
        - mslib
    commands:
        - mswms -h
        - mss -h

about:
    summary: A web service based tool to plan atmospheric research flights
    home: https://bitbucket.org/wxmetvis/mss
    license: Apache 2.0
    license_file: LICENSE

extra:
    recipe-maintainers:
        - ReimarBauer
