[build-system]
requires = ["setuptools >= 40.8.0", "future"]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name = "open-mss"
version = "0.0.0"  # dynamically set in setup.py
description = "MSS - Mission Support System"
readme = "README.md"
license = { text = "Apache-2.0" }
maintainers = [
  { name = "Reimar Bauer", email = "rb.proj@gmail.com" }
]
authors = [
  { name = "Marc Rautenhaus", email = "wxmetvis@posteo.de" }
]
urls = { Homepage = "https://github.com/Open-MSS/MSS" }
requires-python = ">=3.9"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3"
]
dependencies = []  # managed by Pixi
optional-dependencies ={}

[tool.setuptools.packages.find]
include = ["mslib", "mslib.*"]

[project.scripts]
mscolab = "mslib.mscolab.mscolab:main"
mss = "mslib.msui.mss:main"
mssautoplot = "mslib.utils.mssautoplot:main"
msui = "mslib.msui.msui:main"
mswms = "mslib.mswms.mswms:main"
mswms_demodata = "mslib.mswms.demodata:main"

[tool.codespell]
exclude-file = "codespell-ignored-lines.txt"
ignore-words-list = [
    "PRES",
    "degreeE",
    "doubleClick",
    "indexIn",
    "socio-economic",
    "EMAC",
    "emac"
]
