#!/usr/bin/env bash
set -euxo pipefail

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    ffmpeg -framerate 25 -f x11grab -i :99 recording.mp4 &
    recording_pid=$!
elif [[ "$OSTYPE" == "darwin"* ]]; then
    /usr/sbin/screencapture -v -C -k -T0 -g recording.mp4 &
    recording_pid=$!
fi

trap 'kill $recording_pid' EXIT

"$@"
