#!/usr/bin/env bash
set -euxo pipefail

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    ffmpeg -framerate 25 -f x11grab -i :99 recording.mp4 &
    recording_pid=$!
elif [[ "$OSTYPE" == "darwin"* ]]; then
    mkfifo /tmp/srv-input
    cat > /tmp/srv-input &
    cat /tmp/srv-input | /usr/sbin/screencapture -v recording.mp4 &
    recording_pid=$!
fi

trap 'kill $recording_pid' EXIT

"$@"
