[project]
name = "mswms"

description = 'The WMS server of the Mission Support System (MSS) - developed in the community to collaboratively create flight plans based on model data.'
readme = "README.md"
keywords = ["MSS", "WNS", "science", "flight planning"] 
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python",
  "License :: OSI Approved :: Apache-2.0"
]
version = "9.0.0"

source_patches = [
  'build_mswms_setuppy.patch'
]

dependencies = [
  'python',
  'future',
  'defusedxml',
  'basemap >=1.3.3',
  'chameleon',
  'execnet',
  'fastkml >=0.11',
  'shapely >=2.0.0',
  'pygeoif <1.0.0',
  'isodate',
  'lxml',
  'netcdf4',
  'hdf4',
  'pillow',
  'requests >=2.31.0',
  'scipy',
  'owslib >=0.24',
  'unicodecsv',
  'fs',
  'cftime >=1.0.1',
  'matplotlib-base >=3.5.3',
  'flask >=2.3.2',
  'flask-httpauth',
  'werkzeug >=2.2.3, <3.0.0',
  'multidict',
  'pint',
  'markdown',
  'xstatic',
  'xstatic-jquery',
  'xstatic-bootstrap',
  'metpy',
  'pycountry',
  'libtiff <4.5.0',
  'python-slugify',
]

run_constrained = [
  'menuinst >=2.0.2'
]
build_dependencies = [
  'python',
  'pip',
  'setuptools',
  'future',
]

host_dependencies = [
  'python',
  'setuptools',
  'pip',
  'future'
]

authors = ["see AUTHORS"]

maintainers = [
  {name = "ReimarBauer", email = "rb.proj@gmail.com"}
]

test_imports = [
  'mslib'
]
test_commands = [
  'mswms -h',
  'mswms_demodata -h'
]


[project.urls]
Homepage = "https://open-mss.github.io/"
Documentation = "https://mss.rtfd.io"
Repository = "https://github.com/open-mss/MSS"
Issues = "https://github.com/Open-MSS/MSS/issues"
Changelog = "https://github.com/Open-MSS/MSS/blob/stable/CHANGES.rst"
