# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_performance_widget_clientside.ui'
#
# Created by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_PerformanceWidget(object):
    def setupUi(self, PerformanceWidget):
        PerformanceWidget.setObjectName(_fromUtf8("PerformanceWidget"))
        PerformanceWidget.resize(945, 153)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PerformanceWidget.sizePolicy().hasHeightForWidth())
        PerformanceWidget.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtGui.QVBoxLayout(PerformanceWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lblNWPWarning = QtGui.QLabel(PerformanceWidget)
        self.lblNWPWarning.setEnabled(True)
        self.lblNWPWarning.setObjectName(_fromUtf8("lblNWPWarning"))
        self.horizontalLayout_7.addWidget(self.lblNWPWarning)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.btComputePerformance = QtGui.QPushButton(PerformanceWidget)
        self.btComputePerformance.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btComputePerformance.setFont(font)
        self.btComputePerformance.setObjectName(_fromUtf8("btComputePerformance"))
        self.horizontalLayout_7.addWidget(self.btComputePerformance)
        self.btExportToFX = QtGui.QToolButton(PerformanceWidget)
        self.btExportToFX.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.btExportToFX.setAutoRaise(True)
        self.btExportToFX.setArrowType(QtCore.Qt.NoArrow)
        self.btExportToFX.setObjectName(_fromUtf8("btExportToFX"))
        self.horizontalLayout_7.addWidget(self.btExportToFX)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_8 = QtGui.QLabel(PerformanceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.cbAircraft = QtGui.QComboBox(PerformanceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAircraft.sizePolicy().hasHeightForWidth())
        self.cbAircraft.setSizePolicy(sizePolicy)
        self.cbAircraft.setMinimumSize(QtCore.QSize(200, 0))
        self.cbAircraft.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbAircraft.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.cbAircraft.setMinimumContentsLength(0)
        self.cbAircraft.setObjectName(_fromUtf8("cbAircraft"))
        self.cbAircraft.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbAircraft)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_11 = QtGui.QLabel(PerformanceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(100, 0))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.cbAircraftConfig = QtGui.QComboBox(PerformanceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAircraftConfig.sizePolicy().hasHeightForWidth())
        self.cbAircraftConfig.setSizePolicy(sizePolicy)
        self.cbAircraftConfig.setMinimumSize(QtCore.QSize(200, 0))
        self.cbAircraftConfig.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbAircraftConfig.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.cbAircraftConfig.setFrame(True)
        self.cbAircraftConfig.setObjectName(_fromUtf8("cbAircraftConfig"))
        self.cbAircraftConfig.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cbAircraftConfig)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(PerformanceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.dteTakeoffTime = QtGui.QDateTimeEdit(PerformanceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dteTakeoffTime.sizePolicy().hasHeightForWidth())
        self.dteTakeoffTime.setSizePolicy(sizePolicy)
        self.dteTakeoffTime.setMinimumSize(QtCore.QSize(200, 0))
        self.dteTakeoffTime.setDate(QtCore.QDate(2010, 1, 14))
        self.dteTakeoffTime.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(4, 0, 0)))
        self.dteTakeoffTime.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.dteTakeoffTime.setMinimumTime(QtCore.QTime(4, 0, 0))
        self.dteTakeoffTime.setCalendarPopup(False)
        self.dteTakeoffTime.setTimeSpec(QtCore.Qt.UTC)
        self.dteTakeoffTime.setObjectName(_fromUtf8("dteTakeoffTime"))
        self.horizontalLayout_6.addWidget(self.dteTakeoffTime)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(PerformanceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.sbTakeoffWeight = QtGui.QSpinBox(PerformanceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbTakeoffWeight.sizePolicy().hasHeightForWidth())
        self.sbTakeoffWeight.setSizePolicy(sizePolicy)
        self.sbTakeoffWeight.setMinimumSize(QtCore.QSize(200, 0))
        self.sbTakeoffWeight.setMinimum(1)
        self.sbTakeoffWeight.setMaximum(999999)
        self.sbTakeoffWeight.setSingleStep(1000)
        self.sbTakeoffWeight.setProperty("value", 60000)
        self.sbTakeoffWeight.setObjectName(_fromUtf8("sbTakeoffWeight"))
        self.horizontalLayout_4.addWidget(self.sbTakeoffWeight)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(PerformanceWidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_8.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cbUseNWP = QtGui.QCheckBox(PerformanceWidget)
        self.cbUseNWP.setEnabled(True)
        self.cbUseNWP.setMinimumSize(QtCore.QSize(95, 0))
        self.cbUseNWP.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 19, 18))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cbUseNWP.setPalette(palette)
        self.cbUseNWP.setChecked(False)
        self.cbUseNWP.setObjectName(_fromUtf8("cbUseNWP"))
        self.horizontalLayout_5.addWidget(self.cbUseNWP)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.cbCacheEnabled = QtGui.QCheckBox(PerformanceWidget)
        self.cbCacheEnabled.setChecked(True)
        self.cbCacheEnabled.setTristate(False)
        self.cbCacheEnabled.setObjectName(_fromUtf8("cbCacheEnabled"))
        self.horizontalLayout_5.addWidget(self.cbCacheEnabled)
        self.btClearCache = QtGui.QPushButton(PerformanceWidget)
        self.btClearCache.setObjectName(_fromUtf8("btClearCache"))
        self.horizontalLayout_5.addWidget(self.btClearCache)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.cbURL = QtGui.QComboBox(PerformanceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbURL.sizePolicy().hasHeightForWidth())
        self.cbURL.setSizePolicy(sizePolicy)
        self.cbURL.setEditable(True)
        self.cbURL.setObjectName(_fromUtf8("cbURL"))
        self.cbURL.addItem(_fromUtf8(""))
        self.cbURL.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.cbURL)
        self.btConnectNWP = QtGui.QPushButton(PerformanceWidget)
        self.btConnectNWP.setObjectName(_fromUtf8("btConnectNWP"))
        self.horizontalLayout_9.addWidget(self.btConnectNWP)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_9 = QtGui.QLabel(PerformanceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_12.addWidget(self.label_9)
        self.cbWMSLayer = QtGui.QComboBox(PerformanceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbWMSLayer.sizePolicy().hasHeightForWidth())
        self.cbWMSLayer.setSizePolicy(sizePolicy)
        self.cbWMSLayer.setMinimumSize(QtCore.QSize(200, 0))
        self.cbWMSLayer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cbWMSLayer.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.cbWMSLayer.setMinimumContentsLength(0)
        self.cbWMSLayer.setObjectName(_fromUtf8("cbWMSLayer"))
        self.cbWMSLayer.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.cbWMSLayer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(PerformanceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.cbInitTime = QtGui.QComboBox(PerformanceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbInitTime.sizePolicy().hasHeightForWidth())
        self.cbInitTime.setSizePolicy(sizePolicy)
        self.cbInitTime.setMinimumSize(QtCore.QSize(180, 0))
        self.cbInitTime.setObjectName(_fromUtf8("cbInitTime"))
        self.cbInitTime.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cbInitTime)
        self.tbInitTime_cbback = QtGui.QToolButton(PerformanceWidget)
        self.tbInitTime_cbback.setObjectName(_fromUtf8("tbInitTime_cbback"))
        self.horizontalLayout_3.addWidget(self.tbInitTime_cbback)
        self.tbInitTime_cbfwd = QtGui.QToolButton(PerformanceWidget)
        self.tbInitTime_cbfwd.setObjectName(_fromUtf8("tbInitTime_cbfwd"))
        self.horizontalLayout_3.addWidget(self.tbInitTime_cbfwd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)

        self.retranslateUi(PerformanceWidget)
        QtCore.QMetaObject.connectSlotsByName(PerformanceWidget)

    def retranslateUi(self, PerformanceWidget):
        PerformanceWidget.setWindowTitle(
            _translate("PerformanceWidget", "Flight Performance Service Dock Widget", None))
        self.lblNWPWarning.setText(_translate("PerformanceWidget",
                                              "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">NOTE:</span> Wind forecasts are only considered for cruise segments, not for climb/descent segments.</p></body></html>",
                                              None))
        self.btComputePerformance.setToolTip(_translate("PerformanceWidget",
                                                        "Request the computation of the flight performance with the specifed parameters.",
                                                        None))
        self.btComputePerformance.setText(_translate("PerformanceWidget", "compute performance", None))
        self.btExportToFX.setToolTip(
            _translate("PerformanceWidget", "export the flight profile to an FX csv file", None))
        self.btExportToFX.setText(_translate("PerformanceWidget", "...", None))
        self.label_8.setText(_translate("PerformanceWidget", "Aircraft:", None))
        self.cbAircraft.setItemText(0, _translate("PerformanceWidget", "HALO ..", None))
        self.label_11.setText(_translate("PerformanceWidget", "Configuration:", None))
        self.cbAircraftConfig.setToolTip(
            _translate("PerformanceWidget", "Choose an aircraft configuration you would like to use.", None))
        self.cbAircraftConfig.setItemText(0, _translate("PerformanceWidget", "+10 DC", None))
        self.label_3.setText(_translate("PerformanceWidget", "Takeoff time:", None))
        self.dteTakeoffTime.setToolTip(_translate("PerformanceWidget",
                                                  "The time at which you would like the aircraft to be at the waypoint you specify in the edit field to the right.",
                                                  None))
        self.dteTakeoffTime.setDisplayFormat(_translate("PerformanceWidget", "yyyy/MM/dd hh:mm UTC", None))
        self.label_4.setText(_translate("PerformanceWidget", "Takeoff weight:", None))
        self.sbTakeoffWeight.setToolTip(_translate("PerformanceWidget",
                                                   "Either the takeoff weight or the landing weight of the aircraft, depending on the mode you have selected.",
                                                   None))
        self.sbTakeoffWeight.setSuffix(_translate("PerformanceWidget", " lbs", None))
        self.cbUseNWP.setText(_translate("PerformanceWidget", "Use NWP from Web Service:", None))
        self.cbCacheEnabled.setToolTip(_translate("PerformanceWidget",
                                                  "Enable the image cache (retrieved images will be stored locally to speed up repeated retrievals).",
                                                  None))
        self.cbCacheEnabled.setText(_translate("PerformanceWidget", "Cache", None))
        self.btClearCache.setToolTip(_translate("PerformanceWidget", "Clear all cache contents.", None))
        self.btClearCache.setText(_translate("PerformanceWidget", "clear", None))
        self.cbURL.setToolTip(
            _translate("PerformanceWidget", "Enter a valid flight performance service URL here.", None))
        self.cbURL.setItemText(0, _translate("PerformanceWidget", "http://localhost:8002/fc_wms", None))
        self.cbURL.setItemText(1, _translate("PerformanceWidget", "http://osm.omniscale.net/proxy/service", None))
        self.btConnectNWP.setToolTip(_translate("PerformanceWidget", "Request the capabilities from the server.", None))
        self.btConnectNWP.setText(_translate("PerformanceWidget", "connect", None))
        self.label_9.setText(_translate("PerformanceWidget", "Data source:", None))
        self.cbWMSLayer.setItemText(0, _translate("PerformanceWidget", "ECMWF ..", None))
        self.label_5.setText(_translate("PerformanceWidget", "Initialisation:", None))
        self.cbInitTime.setToolTip(_translate("PerformanceWidget",
                                              "If the mode you have selected uses NWP data, select a forecast initialisation time.",
                                              None))
        self.cbInitTime.setItemText(0, _translate("PerformanceWidget", "2010-12-12T00:00:00Z", None))
        self.tbInitTime_cbback.setText(_translate("PerformanceWidget", "<", None))
        self.tbInitTime_cbfwd.setText(_translate("PerformanceWidget", ">", None))
