"""created sharedview table

Revision ID: 3e626f7d30e7
Revises: 4ad0fd989443
Create Date: 2025-09-23 14:33:27.795569

"""
from alembic import op
import sqlalchemy as sa
import mslib.mscolab.custom_migration_types as cu
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '3e626f7d30e7'
down_revision = '4ad0fd989443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharedviews',
    sa.Column('op_id', sa.Integer(), nullable=True),
    sa.Column('u_id', sa.Integer(), nullable=True),
    sa.Column('view_id', sa.String(), nullable=True),
    sa.Column('shared_data', sa.JSON(), nullable=True),
    sa.Column('created_at', cu.AwareDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['op_id'], ['operations.id'], name=op.f('fk_sharedviews_op_id_operations')),
    sa.ForeignKeyConstraint(['u_id'], ['users.id'], name=op.f('fk_sharedviews_u_id_users')),
    sa.PrimaryKeyConstraint('view_id', name=op.f('pk_sharedviews')),
    sa.UniqueConstraint('view_id', name=op.f('uq_sharedviews_view_id'))
    )
    op.drop_table('sharedview')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharedview',
    sa.Column('op_id', sa.INTEGER(), nullable=False),
    sa.Column('u_id', sa.INTEGER(), nullable=False),
    sa.Column('shared_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('view_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['op_id'], ['operations.id'], name='fk_sharedview_op_id_operations'),
    sa.ForeignKeyConstraint(['u_id'], ['users.id'], name='fk_sharedview_u_id_users'),
    sa.PrimaryKeyConstraint('op_id', 'u_id', name='pk_sharedview'),
    sa.UniqueConstraint('view_id', name='uq_sharedview_view_id')
    )
    op.drop_table('sharedviews')
    # ### end Alembic commands ###
