"""viewsettings

Revision ID: 4ad0fd989443
Revises: 922e4d9c94e2
Create Date: 2025-08-29 22:42:02.866220

"""
from alembic import op
import sqlalchemy as sa
import mslib.mscolab.custom_migration_types as cu


# revision identifiers, used by Alembic.
revision = '4ad0fd989443'
down_revision = '922e4d9c94e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewsettings',
    sa.Column('op_id', sa.Integer(), nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', cu.AwareDateTime(), nullable=True),
    sa.Column('updated_at', cu.AwareDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['op_id'], ['operations.id'], name=op.f('fk_viewsettings_op_id_operations')),
    sa.ForeignKeyConstraint(['u_id'], ['users.id'], name=op.f('fk_viewsettings_u_id_users')),
    sa.PrimaryKeyConstraint('op_id', 'u_id', name=op.f('pk_viewsettings')),
    sa.UniqueConstraint('u_id', 'op_id', name='u_id_op_id')
    )
    # ### end Alembic commands ###

    # sharedviews table
    op.create_table(
        'sharedviews',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column('op_id', sa.Integer(), sa.ForeignKey('operations.id'), nullable=False),
        sa.Column('u_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('view_name', sa.String(255), unique=True, nullable=True),
        sa.Column('shared_data', sa.JSON(), nullable=True),
        sa.Column('created_at', cu.AwareDateTime(), nullable=True),
        sa.ForeignKeyConstraint(['op_id'], ['operations.id'], name=op.f('fk_sharedviews_op_id_operations')),
        sa.ForeignKeyConstraint(['u_id'], ['users.id'], name=op.f('fk_sharedviews_u_id_users')),
        sa.UniqueConstraint('view_name', name=op.f('uq_sharedviews_view_name'))
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewsettings')
    # ### end Alembic commands ###
    op.drop_table('sharedviews')
