"""Add ViewSettings table

Revision ID: 5a838b730028
Revises: 922e4d9c94e2
Create Date: 2025-08-08 16:43:00.191487

"""
from alembic import op
import sqlalchemy as sa
import mslib.mscolab.custom_migration_types as cu


# revision identifiers, used by Alembic.
revision = '5a838b730028'
down_revision = '922e4d9c94e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewsettings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('op_id', sa.Integer(), nullable=True),
    sa.Column('u_id', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON()),
    sa.Column('created_at', cu.AwareDateTime(), nullable=True),
    sa.Column('updated_at', cu.AwareDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['op_id'], ['operations.id'], name=op.f('fk_viewsettings_op_id_operations')),
    sa.ForeignKeyConstraint(['u_id'], ['users.id'], name=op.f('fk_viewsettings_u_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_viewsettings')),
    sa.UniqueConstraint('u_id', 'op_id', name='u_id_op_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewsettings')
    # ### end Alembic commands ###
