"""Change ViewSettings to use composite primary key op_id and u_id

Revision ID: 6a11053c5597
Revises: 5a838b730028
Create Date: 2025-08-29 21:01:09.398745

"""
from alembic import op
import sqlalchemy as sa
import mslib.mscolab.custom_migration_types as cu


# revision identifiers, used by Alembic.
revision = '6a11053c5597'
down_revision = '5a838b730028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewsettings', schema=None) as batch_op:
        batch_op.alter_column('op_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('u_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewsettings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('u_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('op_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
