"""To version share_views

Revision ID: 708a96b09d40
Revises: 4ad0fd989443
Create Date: 2025-09-20 23:45:11.743773

"""
from alembic import op
import sqlalchemy as sa
import mslib.mscolab.custom_migration_types as cu


# revision identifiers, used by Alembic.
revision = '708a96b09d40'
down_revision = '4ad0fd989443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharedviews',
    sa.Column('u_id', sa.Integer(), nullable=True),
    sa.Column('shared_data', sa.JSON(), nullable=True),
    sa.Column('created_at', cu.AwareDateTime(), nullable=True),
    sa.Column('op_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['u_id'], ['users.id'], name=op.f('fk_sharedviews_u_id_users')),
    sa.ForeignKeyConstraint(['op_id'], ['operations.id'], name=op.f('fk_sharedviews_op_id_operations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sharedviews')
    # ### end Alembic commands ###
