"""To version <10_0_0>

Revision ID: 3b4e20f78d34
Revises: 89cbaa26ae78
Create Date: 2025-02-06 17:37:12.666326

"""
from alembic import op
import sqlalchemy as sa
import mslib.mscolab.custom_migration_types as cu


# revision identifiers, used by Alembic.
revision = '3b4e20f78d34'
down_revision = 'c171019fe3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fullname',
            sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image_path')
        batch_op.drop_column('fullname')  # Removing fullname column


    # ### end Alembic commands ###
