# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_imageloop_load_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProductChooserDialog(object):
    def setupUi(self, ProductChooserDialog):
        ProductChooserDialog.setObjectName("ProductChooserDialog")
        ProductChooserDialog.resize(372, 187)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProductChooserDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(ProductChooserDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(50, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.cbType = QtWidgets.QComboBox(ProductChooserDialog)
        self.cbType.setObjectName("cbType")
        self.cbType.addItem("")
        self.horizontalLayout.addWidget(self.cbType)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(ProductChooserDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.cbProduct = QtWidgets.QComboBox(ProductChooserDialog)
        self.cbProduct.setObjectName("cbProduct")
        self.cbProduct.addItem("")
        self.horizontalLayout_2.addWidget(self.cbProduct)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(ProductChooserDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(50, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.cbRegion = QtWidgets.QComboBox(ProductChooserDialog)
        self.cbRegion.setObjectName("cbRegion")
        self.cbRegion.addItem("")
        self.horizontalLayout_3.addWidget(self.cbRegion)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(ProductChooserDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.tbInitTime_back = QtWidgets.QToolButton(ProductChooserDialog)
        self.tbInitTime_back.setArrowType(QtCore.Qt.LeftArrow)
        self.tbInitTime_back.setObjectName("tbInitTime_back")
        self.horizontalLayout_4.addWidget(self.tbInitTime_back)
        self.dteInitTime = QtWidgets.QDateTimeEdit(ProductChooserDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dteInitTime.sizePolicy().hasHeightForWidth())
        self.dteInitTime.setSizePolicy(sizePolicy)
        self.dteInitTime.setMinimumSize(QtCore.QSize(140, 0))
        self.dteInitTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dteInitTime.setReadOnly(False)
        self.dteInitTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dteInitTime.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dteInitTime.setCalendarPopup(False)
        self.dteInitTime.setTimeSpec(QtCore.Qt.UTC)
        self.dteInitTime.setObjectName("dteInitTime")
        self.horizontalLayout_4.addWidget(self.dteInitTime)
        self.tbInitTime_fwd = QtWidgets.QToolButton(ProductChooserDialog)
        self.tbInitTime_fwd.setArrowType(QtCore.Qt.RightArrow)
        self.tbInitTime_fwd.setObjectName("tbInitTime_fwd")
        self.horizontalLayout_4.addWidget(self.tbInitTime_fwd)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(ProductChooserDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ProductChooserDialog)
        self.buttonBox.accepted.connect(ProductChooserDialog.accept)
        self.buttonBox.rejected.connect(ProductChooserDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ProductChooserDialog)

    def retranslateUi(self, ProductChooserDialog):
        _translate = QtCore.QCoreApplication.translate
        ProductChooserDialog.setWindowTitle(_translate("ProductChooserDialog", "Product Chooser"))
        self.label_5.setText(_translate("ProductChooserDialog", "Type:"))
        self.cbType.setItemText(0, _translate("ProductChooserDialog", "(type)"))
        self.label_4.setText(_translate("ProductChooserDialog", "Product:"))
        self.cbProduct.setItemText(0, _translate("ProductChooserDialog", "(product)"))
        self.label_6.setText(_translate("ProductChooserDialog", "Region:"))
        self.cbRegion.setItemText(0, _translate("ProductChooserDialog", "(region)"))
        self.label_2.setText(_translate("ProductChooserDialog", "Initialisation:"))
        self.tbInitTime_back.setText(_translate("ProductChooserDialog", "<<"))
        self.dteInitTime.setDisplayFormat(_translate("ProductChooserDialog", "yyyy-MM-dd hh:mm UTC"))
        self.tbInitTime_fwd.setText(_translate("ProductChooserDialog", ">>"))

