# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_imageloop_widget.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from builtins import object
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ImageLoopWidget(object):
    def setupUi(self, ImageLoopWidget):
        ImageLoopWidget.setObjectName("ImageLoopWidget")
        ImageLoopWidget.resize(553, 393)
        ImageLoopWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImageLoopWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(ImageLoopWidget)
        self.frame.setMinimumSize(QtCore.QSize(120, 22))
        self.frame.setMaximumSize(QtCore.QSize(120, 14))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.btZoomIn = QtWidgets.QToolButton(self.frame)
        self.btZoomIn.setGeometry(QtCore.QRect(0, 1, 20, 20))
        self.btZoomIn.setMinimumSize(QtCore.QSize(20, 20))
        self.btZoomIn.setMaximumSize(QtCore.QSize(20, 20))
        self.btZoomIn.setAutoRaise(True)
        self.btZoomIn.setObjectName("btZoomIn")
        self.btZoomOut = QtWidgets.QToolButton(self.frame)
        self.btZoomOut.setGeometry(QtCore.QRect(17, 1, 20, 20))
        self.btZoomOut.setMinimumSize(QtCore.QSize(20, 20))
        self.btZoomOut.setMaximumSize(QtCore.QSize(20, 20))
        self.btZoomOut.setAutoRaise(True)
        self.btZoomOut.setObjectName("btZoomOut")
        self.btZoomNormalSize = QtWidgets.QToolButton(self.frame)
        self.btZoomNormalSize.setGeometry(QtCore.QRect(38, 1, 30, 20))
        self.btZoomNormalSize.setMinimumSize(QtCore.QSize(30, 20))
        self.btZoomNormalSize.setMaximumSize(QtCore.QSize(30, 20))
        self.btZoomNormalSize.setCheckable(False)
        self.btZoomNormalSize.setAutoRaise(True)
        self.btZoomNormalSize.setObjectName("btZoomNormalSize")
        self.btFitToWindow = QtWidgets.QToolButton(self.frame)
        self.btFitToWindow.setGeometry(QtCore.QRect(67, 1, 25, 20))
        self.btFitToWindow.setMinimumSize(QtCore.QSize(25, 20))
        self.btFitToWindow.setMaximumSize(QtCore.QSize(25, 14))
        self.btFitToWindow.setCheckable(True)
        self.btFitToWindow.setAutoRaise(True)
        self.btFitToWindow.setObjectName("btFitToWindow")
        self.tbLevel_down = QtWidgets.QToolButton(self.frame)
        self.tbLevel_down.setGeometry(QtCore.QRect(92, 8, 25, 14))
        self.tbLevel_down.setMinimumSize(QtCore.QSize(25, 14))
        self.tbLevel_down.setMaximumSize(QtCore.QSize(30, 14))
        self.tbLevel_down.setAutoRaise(True)
        self.tbLevel_down.setArrowType(QtCore.Qt.DownArrow)
        self.tbLevel_down.setObjectName("tbLevel_down")
        self.tbLevel_up = QtWidgets.QToolButton(self.frame)
        self.tbLevel_up.setGeometry(QtCore.QRect(92, -1, 25, 14))
        self.tbLevel_up.setMinimumSize(QtCore.QSize(25, 14))
        self.tbLevel_up.setMaximumSize(QtCore.QSize(30, 14))
        self.tbLevel_up.setAutoRaise(True)
        self.tbLevel_up.setArrowType(QtCore.Qt.UpArrow)
        self.tbLevel_up.setObjectName("tbLevel_up")
        self.horizontalLayout_2.addWidget(self.frame)
        self.lblInfo = QtWidgets.QLabel(ImageLoopWidget)
        self.lblInfo.setMinimumSize(QtCore.QSize(0, 20))
        self.lblInfo.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.lblInfo.setFont(font)
        self.lblInfo.setObjectName("lblInfo")
        self.horizontalLayout_2.addWidget(self.lblInfo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(ImageLoopWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 539, 351))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(ImageLoopWidget)
        QtCore.QMetaObject.connectSlotsByName(ImageLoopWidget)

    def retranslateUi(self, ImageLoopWidget):
        _translate = QtCore.QCoreApplication.translate
        ImageLoopWidget.setWindowTitle(_translate("ImageLoopWidget", "Form"))
        self.btZoomIn.setToolTip(_translate("ImageLoopWidget", "zoom in"))
        self.btZoomIn.setText(_translate("ImageLoopWidget", "+"))
        self.btZoomOut.setToolTip(_translate("ImageLoopWidget", "zoom out"))
        self.btZoomOut.setText(_translate("ImageLoopWidget", "-"))
        self.btZoomNormalSize.setToolTip(_translate("ImageLoopWidget", "reset image size to original size"))
        self.btZoomNormalSize.setText(_translate("ImageLoopWidget", "orig"))
        self.btFitToWindow.setToolTip(_translate("ImageLoopWidget", "fit image size to window"))
        self.btFitToWindow.setText(_translate("ImageLoopWidget", "fit"))
        self.tbLevel_down.setToolTip(_translate("ImageLoopWidget", "decrease level"))
        self.tbLevel_down.setText(_translate("ImageLoopWidget", "\\/"))
        self.tbLevel_up.setToolTip(_translate("ImageLoopWidget", "increase level"))
        self.tbLevel_up.setText(_translate("ImageLoopWidget", "/\\"))
        self.lblInfo.setText(_translate("ImageLoopWidget", "<Product Information>"))

