# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_loopwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ImageLoopWindow(object):
    def setupUi(self, ImageLoopWindow):
        ImageLoopWindow.setObjectName("ImageLoopWindow")
        ImageLoopWindow.resize(1042, 717)
        ImageLoopWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(ImageLoopWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.dteValidTime = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dteValidTime.setMinimumSize(QtCore.QSize(220, 0))
        self.dteValidTime.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.dteValidTime.setFont(font)
        self.dteValidTime.setReadOnly(True)
        self.dteValidTime.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dteValidTime.setDate(QtCore.QDate(2010, 1, 22))
        self.dteValidTime.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(12, 0, 0)))
        self.dteValidTime.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.dteValidTime.setMinimumTime(QtCore.QTime(12, 0, 0))
        self.dteValidTime.setCalendarPopup(False)
        self.dteValidTime.setTimeSpec(QtCore.Qt.UTC)
        self.dteValidTime.setObjectName("dteValidTime")
        self.horizontalLayout_3.addWidget(self.dteValidTime)
        self.tbValidTime_back = QtWidgets.QToolButton(self.centralwidget)
        self.tbValidTime_back.setArrowType(QtCore.Qt.LeftArrow)
        self.tbValidTime_back.setObjectName("tbValidTime_back")
        self.horizontalLayout_3.addWidget(self.tbValidTime_back)
        self.cbVTStep = QtWidgets.QComboBox(self.centralwidget)
        self.cbVTStep.setObjectName("cbVTStep")
        self.cbVTStep.addItem("")
        self.cbVTStep.addItem("")
        self.cbVTStep.addItem("")
        self.cbVTStep.addItem("")
        self.cbVTStep.addItem("")
        self.cbVTStep.addItem("")
        self.cbVTStep.addItem("")
        self.cbVTStep.addItem("")
        self.cbVTStep.addItem("")
        self.horizontalLayout_3.addWidget(self.cbVTStep)
        self.tbValidTime_fwd = QtWidgets.QToolButton(self.centralwidget)
        self.tbValidTime_fwd.setArrowType(QtCore.Qt.RightArrow)
        self.tbValidTime_fwd.setObjectName("tbValidTime_fwd")
        self.horizontalLayout_3.addWidget(self.tbValidTime_fwd)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.centralFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralFrame.sizePolicy().hasHeightForWidth())
        self.centralFrame.setSizePolicy(sizePolicy)
        self.centralFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.centralFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.centralFrame.setObjectName("centralFrame")
        self.verticalLayout.addWidget(self.centralFrame)
        ImageLoopWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImageLoopWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 26))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Layout = QtWidgets.QMenu(self.menubar)
        self.menu_Layout.setObjectName("menu_Layout")
        ImageLoopWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(ImageLoopWindow)
        self.statusBar.setObjectName("statusBar")
        ImageLoopWindow.setStatusBar(self.statusBar)
        self.actionE_xit = QtWidgets.QAction(ImageLoopWindow)
        self.actionE_xit.setObjectName("actionE_xit")
        self.actionSingleView = QtWidgets.QAction(ImageLoopWindow)
        self.actionSingleView.setObjectName("actionSingleView")
        self.actionDualView = QtWidgets.QAction(ImageLoopWindow)
        self.actionDualView.setObjectName("actionDualView")
        self.actionOneLargeTwoSmall = QtWidgets.QAction(ImageLoopWindow)
        self.actionOneLargeTwoSmall.setObjectName("actionOneLargeTwoSmall")
        self.actionOneLargeThreeSmall = QtWidgets.QAction(ImageLoopWindow)
        self.actionOneLargeThreeSmall.setObjectName("actionOneLargeThreeSmall")
        self.actionQuadView = QtWidgets.QAction(ImageLoopWindow)
        self.actionQuadView.setObjectName("actionQuadView")
        self.menu_File.addAction(self.actionE_xit)
        self.menu_Layout.addAction(self.actionSingleView)
        self.menu_Layout.addAction(self.actionDualView)
        self.menu_Layout.addAction(self.actionOneLargeTwoSmall)
        self.menu_Layout.addAction(self.actionOneLargeThreeSmall)
        self.menu_Layout.addAction(self.actionQuadView)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Layout.menuAction())

        self.retranslateUi(ImageLoopWindow)
        self.actionE_xit.triggered.connect(ImageLoopWindow.close)
        QtCore.QMetaObject.connectSlotsByName(ImageLoopWindow)

    def retranslateUi(self, ImageLoopWindow):
        _translate = QtCore.QCoreApplication.translate
        ImageLoopWindow.setWindowTitle(_translate("ImageLoopWindow", "Loop View - Mission Support System"))
        self.label_3.setText(_translate("ImageLoopWindow", "Synchronized Valid Time:"))
        self.dteValidTime.setDisplayFormat(_translate("ImageLoopWindow", "yyyy-MM-dd hh:mm UTC"))
        self.tbValidTime_back.setToolTip(_translate("ImageLoopWindow", "decrement time"))
        self.tbValidTime_back.setText(_translate("ImageLoopWindow", "<<"))
        self.cbVTStep.setToolTip(_translate("ImageLoopWindow", "time step for changing the valid time"))
        self.cbVTStep.setItemText(0, _translate("ImageLoopWindow", "5 min"))
        self.cbVTStep.setItemText(1, _translate("ImageLoopWindow", "10 min"))
        self.cbVTStep.setItemText(2, _translate("ImageLoopWindow", "15 min"))
        self.cbVTStep.setItemText(3, _translate("ImageLoopWindow", "30 min"))
        self.cbVTStep.setItemText(4, _translate("ImageLoopWindow", "1 hour"))
        self.cbVTStep.setItemText(5, _translate("ImageLoopWindow", "3 hours"))
        self.cbVTStep.setItemText(6, _translate("ImageLoopWindow", "6 hours"))
        self.cbVTStep.setItemText(7, _translate("ImageLoopWindow", "12 hours"))
        self.cbVTStep.setItemText(8, _translate("ImageLoopWindow", "24 hours"))
        self.tbValidTime_fwd.setToolTip(_translate("ImageLoopWindow", "increment time"))
        self.tbValidTime_fwd.setText(_translate("ImageLoopWindow", ">>"))
        self.menu_File.setTitle(_translate("ImageLoopWindow", "&File"))
        self.menu_Layout.setTitle(_translate("ImageLoopWindow", "&Layout"))
        self.actionE_xit.setText(_translate("ImageLoopWindow", "E&xit Module"))
        self.actionE_xit.setShortcut(_translate("ImageLoopWindow", "Ctrl+X"))
        self.actionSingleView.setText(_translate("ImageLoopWindow", "&Single View"))
        self.actionSingleView.setShortcut(_translate("ImageLoopWindow", "Alt+1"))
        self.actionDualView.setText(_translate("ImageLoopWindow", "&Dual View"))
        self.actionDualView.setShortcut(_translate("ImageLoopWindow", "Alt+2"))
        self.actionOneLargeTwoSmall.setText(_translate("ImageLoopWindow", "&One Large, Two Small"))
        self.actionOneLargeTwoSmall.setShortcut(_translate("ImageLoopWindow", "Alt+3"))
        self.actionOneLargeThreeSmall.setText(_translate("ImageLoopWindow", "One &Large, Three Small"))
        self.actionOneLargeThreeSmall.setShortcut(_translate("ImageLoopWindow", "Alt+4"))
        self.actionQuadView.setText(_translate("ImageLoopWindow", "&Quad View"))
        self.actionQuadView.setShortcut(_translate("ImageLoopWindow", "Alt+5"))

