# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mslib/msui/ui/ui_mscolab_admin_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MscolabAdminWindow(object):
    def setupUi(self, MscolabAdminWindow):
        MscolabAdminWindow.setObjectName("MscolabAdminWindow")
        MscolabAdminWindow.resize(963, 736)
        self.centralwidget = QtWidgets.QWidget(MscolabAdminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 961, 621))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.projectNameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.horizontalLayout.addWidget(self.projectNameLabel)
        self.usernameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.usernameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usernameLabel.setObjectName("usernameLabel")
        self.horizontalLayout.addWidget(self.usernameLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addUsersSearch = QtWidgets.QLineEdit(self.layoutWidget)
        self.addUsersSearch.setObjectName("addUsersSearch")
        self.horizontalLayout_2.addWidget(self.addUsersSearch)
        self.selectAllAddBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.selectAllAddBtn.setObjectName("selectAllAddBtn")
        self.horizontalLayout_2.addWidget(self.selectAllAddBtn)
        self.deselectAllAddBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.deselectAllAddBtn.setObjectName("deselectAllAddBtn")
        self.horizontalLayout_2.addWidget(self.deselectAllAddBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.addUsersTable = QtWidgets.QTableWidget(self.layoutWidget)
        self.addUsersTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.addUsersTable.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.addUsersTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.addUsersTable.setObjectName("addUsersTable")
        self.addUsersTable.setColumnCount(2)
        self.addUsersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.addUsersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.addUsersTable.setHorizontalHeaderItem(1, item)
        self.addUsersTable.horizontalHeader().setStretchLastSection(True)
        self.addUsersTable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.addUsersTable)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addUsersPermission = QtWidgets.QComboBox(self.layoutWidget)
        self.addUsersPermission.setObjectName("addUsersPermission")
        self.addUsersPermission.addItem("")
        self.addUsersPermission.addItem("")
        self.addUsersPermission.addItem("")
        self.horizontalLayout_3.addWidget(self.addUsersPermission)
        self.addUsersBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.addUsersBtn.setObjectName("addUsersBtn")
        self.horizontalLayout_3.addWidget(self.addUsersBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.modifyUsersSearch = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modifyUsersSearch.sizePolicy().hasHeightForWidth())
        self.modifyUsersSearch.setSizePolicy(sizePolicy)
        self.modifyUsersSearch.setObjectName("modifyUsersSearch")
        self.horizontalLayout_4.addWidget(self.modifyUsersSearch)
        self.modifyUsersPermissionFilter = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modifyUsersPermissionFilter.sizePolicy().hasHeightForWidth())
        self.modifyUsersPermissionFilter.setSizePolicy(sizePolicy)
        self.modifyUsersPermissionFilter.setObjectName("modifyUsersPermissionFilter")
        self.modifyUsersPermissionFilter.addItem("")
        self.modifyUsersPermissionFilter.addItem("")
        self.modifyUsersPermissionFilter.addItem("")
        self.modifyUsersPermissionFilter.addItem("")
        self.horizontalLayout_4.addWidget(self.modifyUsersPermissionFilter)
        self.selectAllModifyBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.selectAllModifyBtn.setObjectName("selectAllModifyBtn")
        self.horizontalLayout_4.addWidget(self.selectAllModifyBtn)
        self.deselectAllModifyBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.deselectAllModifyBtn.setObjectName("deselectAllModifyBtn")
        self.horizontalLayout_4.addWidget(self.deselectAllModifyBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.modifyUsersTable = QtWidgets.QTableWidget(self.layoutWidget)
        self.modifyUsersTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.modifyUsersTable.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.modifyUsersTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.modifyUsersTable.setObjectName("modifyUsersTable")
        self.modifyUsersTable.setColumnCount(3)
        self.modifyUsersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.modifyUsersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.modifyUsersTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.modifyUsersTable.setHorizontalHeaderItem(2, item)
        self.modifyUsersTable.horizontalHeader().setStretchLastSection(True)
        self.modifyUsersTable.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.modifyUsersTable)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.modifyUsersPermission = QtWidgets.QComboBox(self.layoutWidget)
        self.modifyUsersPermission.setObjectName("modifyUsersPermission")
        self.modifyUsersPermission.addItem("")
        self.modifyUsersPermission.addItem("")
        self.modifyUsersPermission.addItem("")
        self.horizontalLayout_5.addWidget(self.modifyUsersPermission)
        self.modifyUsersBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.modifyUsersBtn.setObjectName("modifyUsersBtn")
        self.horizontalLayout_5.addWidget(self.modifyUsersBtn)
        self.deleteUsersBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.deleteUsersBtn.setObjectName("deleteUsersBtn")
        self.horizontalLayout_5.addWidget(self.deleteUsersBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        MscolabAdminWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MscolabAdminWindow)
        self.statusbar.setObjectName("statusbar")
        MscolabAdminWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MscolabAdminWindow)
        QtCore.QMetaObject.connectSlotsByName(MscolabAdminWindow)

    def retranslateUi(self, MscolabAdminWindow):
        _translate = QtCore.QCoreApplication.translate
        MscolabAdminWindow.setWindowTitle(_translate("MscolabAdminWindow", "Admin Window"))
        self.projectNameLabel.setText(_translate("MscolabAdminWindow", "Project: "))
        self.usernameLabel.setText(_translate("MscolabAdminWindow", "Logged In: "))
        self.label.setText(_translate("MscolabAdminWindow", "All Users Without Permission:"))
        self.addUsersSearch.setPlaceholderText(_translate("MscolabAdminWindow", "Search User"))
        self.selectAllAddBtn.setText(_translate("MscolabAdminWindow", "Select All"))
        self.deselectAllAddBtn.setText(_translate("MscolabAdminWindow", "Deselect All"))
        item = self.addUsersTable.horizontalHeaderItem(0)
        item.setText(_translate("MscolabAdminWindow", "Username"))
        item = self.addUsersTable.horizontalHeaderItem(1)
        item.setText(_translate("MscolabAdminWindow", "Email"))
        self.addUsersPermission.setItemText(0, _translate("MscolabAdminWindow", "admin"))
        self.addUsersPermission.setItemText(1, _translate("MscolabAdminWindow", "collaborator"))
        self.addUsersPermission.setItemText(2, _translate("MscolabAdminWindow", "viewer"))
        self.addUsersBtn.setText(_translate("MscolabAdminWindow", "Add"))
        self.label_2.setText(_translate("MscolabAdminWindow", "All Users With Permission:"))
        self.modifyUsersSearch.setPlaceholderText(_translate("MscolabAdminWindow", "Search User"))
        self.modifyUsersPermissionFilter.setItemText(0, _translate("MscolabAdminWindow", "all"))
        self.modifyUsersPermissionFilter.setItemText(1, _translate("MscolabAdminWindow", "admin"))
        self.modifyUsersPermissionFilter.setItemText(2, _translate("MscolabAdminWindow", "collaborator"))
        self.modifyUsersPermissionFilter.setItemText(3, _translate("MscolabAdminWindow", "viewer"))
        self.selectAllModifyBtn.setText(_translate("MscolabAdminWindow", "Select All"))
        self.deselectAllModifyBtn.setText(_translate("MscolabAdminWindow", "Deselect All"))
        item = self.modifyUsersTable.horizontalHeaderItem(0)
        item.setText(_translate("MscolabAdminWindow", "Username"))
        item = self.modifyUsersTable.horizontalHeaderItem(1)
        item.setText(_translate("MscolabAdminWindow", "Email"))
        item = self.modifyUsersTable.horizontalHeaderItem(2)
        item.setText(_translate("MscolabAdminWindow", "Permission"))
        self.modifyUsersPermission.setItemText(0, _translate("MscolabAdminWindow", "admin"))
        self.modifyUsersPermission.setItemText(1, _translate("MscolabAdminWindow", "collaborator"))
        self.modifyUsersPermission.setItemText(2, _translate("MscolabAdminWindow", "viewer"))
        self.modifyUsersBtn.setText(_translate("MscolabAdminWindow", "Modify"))
        self.deleteUsersBtn.setText(_translate("MscolabAdminWindow", "Delete"))

