# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MSSMainWindow(object):
    def setupUi(self, MSSMainWindow):
        MSSMainWindow.setObjectName("MSSMainWindow")
        MSSMainWindow.resize(424, 540)
        self.centralwidget = QtWidgets.QWidget(MSSMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lblActiveFlightTrack = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblActiveFlightTrack.sizePolicy().hasHeightForWidth())
        self.lblActiveFlightTrack.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lblActiveFlightTrack.setFont(font)
        self.lblActiveFlightTrack.setFrameShape(QtWidgets.QFrame.Box)
        self.lblActiveFlightTrack.setObjectName("lblActiveFlightTrack")
        self.horizontalLayout_2.addWidget(self.lblActiveFlightTrack)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.listFlightTracks = QtWidgets.QListWidget(self.groupBox_3)
        self.listFlightTracks.setAlternatingRowColors(True)
        self.listFlightTracks.setTextElideMode(QtCore.Qt.ElideNone)
        self.listFlightTracks.setObjectName("listFlightTracks")
        self.verticalLayout_6.addWidget(self.listFlightTracks)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btSelectFlightTrack = QtWidgets.QPushButton(self.groupBox_3)
        self.btSelectFlightTrack.setObjectName("btSelectFlightTrack")
        self.horizontalLayout_3.addWidget(self.btSelectFlightTrack)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listViews = QtWidgets.QListWidget(self.groupBox)
        self.listViews.setObjectName("listViews")
        self.verticalLayout_4.addWidget(self.listViews)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listTools = QtWidgets.QListWidget(self.groupBox_2)
        self.listTools.setObjectName("listTools")
        self.verticalLayout_5.addWidget(self.listTools)
        self.verticalLayout.addWidget(self.groupBox_2)
        MSSMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MSSMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 424, 26))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuImport_Flight_Track = QtWidgets.QMenu(self.menu_File)
        self.menuImport_Flight_Track.setObjectName("menuImport_Flight_Track")
        self.menuExport_Active_Flight_Track = QtWidgets.QMenu(self.menu_File)
        self.menuExport_Active_Flight_Track.setObjectName("menuExport_Active_Flight_Track")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        self.menu_Tools = QtWidgets.QMenu(self.menubar)
        self.menu_Tools.setObjectName("menu_Tools")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MSSMainWindow.setMenuBar(self.menubar)
        self.action_Quit = QtWidgets.QAction(MSSMainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.actionNewFlightTrack = QtWidgets.QAction(MSSMainWindow)
        self.actionNewFlightTrack.setObjectName("actionNewFlightTrack")
        self.actionOpenFlightTrack = QtWidgets.QAction(MSSMainWindow)
        self.actionOpenFlightTrack.setObjectName("actionOpenFlightTrack")
        self.actionSaveActiveFlightTrack = QtWidgets.QAction(MSSMainWindow)
        self.actionSaveActiveFlightTrack.setObjectName("actionSaveActiveFlightTrack")
        self.actionSaveActiveFlightTrackAs = QtWidgets.QAction(MSSMainWindow)
        self.actionSaveActiveFlightTrackAs.setObjectName("actionSaveActiveFlightTrackAs")
        self.actionCloseSelectedFlightTrack = QtWidgets.QAction(MSSMainWindow)
        self.actionCloseSelectedFlightTrack.setObjectName("actionCloseSelectedFlightTrack")
        self.actionTopView = QtWidgets.QAction(MSSMainWindow)
        self.actionTopView.setObjectName("actionTopView")
        self.actionSideView = QtWidgets.QAction(MSSMainWindow)
        self.actionSideView.setObjectName("actionSideView")
        self.actionTableView = QtWidgets.QAction(MSSMainWindow)
        self.actionTableView.setObjectName("actionTableView")
        self.actionLoopView = QtWidgets.QAction(MSSMainWindow)
        self.actionLoopView.setObjectName("actionLoopView")
        self.actionTimeSeriesViewTrajectories = QtWidgets.QAction(MSSMainWindow)
        self.actionTimeSeriesViewTrajectories.setObjectName("actionTimeSeriesViewTrajectories")
        self.actionTrajectoryToolLagranto = QtWidgets.QAction(MSSMainWindow)
        self.actionTrajectoryToolLagranto.setObjectName("actionTrajectoryToolLagranto")
        self.actionAboutMSUI = QtWidgets.QAction(MSSMainWindow)
        self.actionAboutMSUI.setObjectName("actionAboutMSUI")
        self.actionLoad_Configuration = QtWidgets.QAction(MSSMainWindow)
        self.actionLoad_Configuration.setObjectName("actionLoad_Configuration")
        self.actionOnlineHelp = QtWidgets.QAction(MSSMainWindow)
        self.actionOnlineHelp.setObjectName("actionOnlineHelp")
        self.menu_File.addAction(self.actionNewFlightTrack)
        self.menu_File.addAction(self.actionOpenFlightTrack)
        self.menu_File.addAction(self.actionCloseSelectedFlightTrack)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSaveActiveFlightTrack)
        self.menu_File.addAction(self.actionSaveActiveFlightTrackAs)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.menuImport_Flight_Track.menuAction())
        self.menu_File.addAction(self.menuExport_Active_Flight_Track.menuAction())
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionLoad_Configuration)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_View.addAction(self.actionTopView)
        self.menu_View.addAction(self.actionSideView)
        self.menu_View.addAction(self.actionTableView)
        self.menu_Tools.addAction(self.actionTrajectoryToolLagranto)
        self.menu_Tools.addAction(self.actionTimeSeriesViewTrajectories)
        self.menu_Tools.addSeparator()
        self.menu_Tools.addAction(self.actionLoopView)
        self.menu_Help.addAction(self.actionOnlineHelp)
        self.menu_Help.addAction(self.actionAboutMSUI)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MSSMainWindow)
        self.action_Quit.triggered.connect(MSSMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MSSMainWindow)

    def retranslateUi(self, MSSMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MSSMainWindow.setWindowTitle(_translate("MSSMainWindow", "Mission Support System"))
        self.groupBox_3.setTitle(_translate("MSSMainWindow", "Flight Tracks:"))
        self.label_3.setText(_translate("MSSMainWindow", "Active flight track:"))
        self.lblActiveFlightTrack.setText(_translate("MSSMainWindow", "(active flight track)"))
        self.label_2.setText(_translate("MSSMainWindow", "Open flight tracks:"))
        self.listFlightTracks.setToolTip(_translate("MSSMainWindow", "List of open flight tracks.\n"
"Double-click a flight track to rename it."))
        self.btSelectFlightTrack.setText(_translate("MSSMainWindow", "set selected flight track active"))
        self.groupBox.setTitle(_translate("MSSMainWindow", "Open Views:"))
        self.listViews.setToolTip(_translate("MSSMainWindow", "Double-click a view to bring it to the front."))
        self.groupBox_2.setTitle(_translate("MSSMainWindow", "Open Tools:"))
        self.listTools.setToolTip(_translate("MSSMainWindow", "Double-click a tool to bring it to the front."))
        self.menu_File.setTitle(_translate("MSSMainWindow", "&File"))
        self.menuImport_Flight_Track.setTitle(_translate("MSSMainWindow", "Import Flight Track"))
        self.menuExport_Active_Flight_Track.setTitle(_translate("MSSMainWindow", "Export Active Flight Track"))
        self.menu_View.setTitle(_translate("MSSMainWindow", "&Views"))
        self.menu_Tools.setTitle(_translate("MSSMainWindow", "&Tools"))
        self.menu_Help.setTitle(_translate("MSSMainWindow", "&Help"))
        self.action_Quit.setText(_translate("MSSMainWindow", "&Quit"))
        self.action_Quit.setShortcut(_translate("MSSMainWindow", "Ctrl+Q"))
        self.actionNewFlightTrack.setText(_translate("MSSMainWindow", "&New Flight Track..."))
        self.actionNewFlightTrack.setShortcut(_translate("MSSMainWindow", "Ctrl+N"))
        self.actionOpenFlightTrack.setText(_translate("MSSMainWindow", "&Open Flight Track..."))
        self.actionOpenFlightTrack.setShortcut(_translate("MSSMainWindow", "Ctrl+O"))
        self.actionSaveActiveFlightTrack.setText(_translate("MSSMainWindow", "&Save Active Flight Track"))
        self.actionSaveActiveFlightTrack.setShortcut(_translate("MSSMainWindow", "Ctrl+S"))
        self.actionSaveActiveFlightTrackAs.setText(_translate("MSSMainWindow", "Save Active Flight Track &As..."))
        self.actionCloseSelectedFlightTrack.setText(_translate("MSSMainWindow", "&Close Selected Flight Track"))
        self.actionTopView.setText(_translate("MSSMainWindow", "&Top View (Horizontal Section)"))
        self.actionSideView.setText(_translate("MSSMainWindow", "&Side View (Vertical Section)"))
        self.actionTableView.setText(_translate("MSSMainWindow", "T&able View"))
        self.actionLoopView.setText(_translate("MSSMainWindow", "&Loop View (Images)"))
        self.actionTimeSeriesViewTrajectories.setText(_translate("MSSMainWindow", "T&ime Series View (Trajectories)"))
        self.actionTrajectoryToolLagranto.setText(_translate("MSSMainWindow", "&Trajectory Tool (Lagranto)"))
        self.actionAboutMSUI.setText(_translate("MSSMainWindow", "&About MSS"))
        self.actionLoad_Configuration.setText(_translate("MSSMainWindow", "Load Configuration"))
        self.actionOnlineHelp.setText(_translate("MSSMainWindow", "Online &Help"))

