# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mslib/msui/ui/ui_mscolab_project_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MscolabProject(object):
    def setupUi(self, MscolabProject):
        MscolabProject.setObjectName("MscolabProject")
        MscolabProject.resize(990, 826)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MscolabProject.sizePolicy().hasHeightForWidth())
        MscolabProject.setSizePolicy(sizePolicy)
        MscolabProject.setMinimumSize(QtCore.QSize(990, 802))
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(MscolabProject)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 991, 828))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.username = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.username.setMinimumSize(QtCore.QSize(408, 0))
        self.username.setObjectName("username")
        self.horizontalLayout.addWidget(self.username)
        self.accessLevel = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.accessLevel.setObjectName("accessLevel")
        self.accessLevel.addItem("")
        self.accessLevel.addItem("")
        self.accessLevel.addItem("")
        self.horizontalLayout.addWidget(self.accessLevel)
        self.add = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.add.setObjectName("add")
        self.horizontalLayout.addWidget(self.add)
        self.modify = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.modify.setObjectName("modify")
        self.horizontalLayout.addWidget(self.modify)
        self.delete_1 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.delete_1.setObjectName("delete_1")
        self.horizontalLayout.addWidget(self.delete_1)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.proj_info = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.proj_info.setText("")
        self.proj_info.setObjectName("proj_info")
        self.verticalLayout_4.addWidget(self.proj_info)
        self.user_info = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.user_info.setText("")
        self.user_info.setObjectName("user_info")
        self.verticalLayout_4.addWidget(self.user_info)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.collaboratorsList = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collaboratorsList.sizePolicy().hasHeightForWidth())
        self.collaboratorsList.setSizePolicy(sizePolicy)
        self.collaboratorsList.setMinimumSize(QtCore.QSize(200, 300))
        self.collaboratorsList.setObjectName("collaboratorsList")
        self.horizontalLayout_3.addWidget(self.collaboratorsList)
        self.messages = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messages.sizePolicy().hasHeightForWidth())
        self.messages.setSizePolicy(sizePolicy)
        self.messages.setMinimumSize(QtCore.QSize(256, 300))
        self.messages.setObjectName("messages")
        self.horizontalLayout_3.addWidget(self.messages)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.messageText = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_3)
        self.messageText.setMinimumSize(QtCore.QSize(700, 100))
        self.messageText.setObjectName("messageText")
        self.horizontalLayout_2.addWidget(self.messageText)
        self.sendMessage = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.sendMessage.setObjectName("sendMessage")
        self.horizontalLayout_2.addWidget(self.sendMessage)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.changes = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        self.changes.setMinimumSize(QtCore.QSize(521, 300))
        self.changes.setObjectName("changes")
        self.verticalLayout.addWidget(self.changes)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.checkout = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.checkout.setObjectName("checkout")
        self.horizontalLayout_4.addWidget(self.checkout)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout)

        self.retranslateUi(MscolabProject)
        QtCore.QMetaObject.connectSlotsByName(MscolabProject)

    def retranslateUi(self, MscolabProject):
        _translate = QtCore.QCoreApplication.translate
        MscolabProject.setWindowTitle(_translate("MscolabProject", "Mscolab Project"))
        self.accessLevel.setItemText(0, _translate("MscolabProject", "collaborator"))
        self.accessLevel.setItemText(1, _translate("MscolabProject", "admin"))
        self.accessLevel.setItemText(2, _translate("MscolabProject", "viewer"))
        self.add.setText(_translate("MscolabProject", "add"))
        self.modify.setText(_translate("MscolabProject", "modify"))
        self.delete_1.setText(_translate("MscolabProject", "delete"))
        self.messageText.setPlaceholderText(_translate("MscolabProject", "Enter message here"))
        self.sendMessage.setText(_translate("MscolabProject", "send"))
        self.checkout.setText(_translate("MscolabProject", "checkout"))

