# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mslib/msui/ui/ui_mscolab_profile_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfileWindow(object):
    def setupUi(self, ProfileWindow):
        ProfileWindow.setObjectName("ProfileWindow")
        ProfileWindow.resize(242, 202)
        self.gridLayout = QtWidgets.QGridLayout(ProfileWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.infoGl = QtWidgets.QGridLayout()
        self.infoGl.setObjectName("infoGl")
        self.usernameLabel_2 = QtWidgets.QLabel(ProfileWindow)
        self.usernameLabel_2.setText("")
        self.usernameLabel_2.setObjectName("usernameLabel_2")
        self.infoGl.addWidget(self.usernameLabel_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(ProfileWindow)
        self.label.setObjectName("label")
        self.infoGl.addWidget(self.label, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_3 = QtWidgets.QLabel(ProfileWindow)
        self.label_3.setObjectName("label_3")
        self.infoGl.addWidget(self.label_3, 4, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_2 = QtWidgets.QLabel(ProfileWindow)
        self.label_2.setObjectName("label_2")
        self.infoGl.addWidget(self.label_2, 3, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.nickname_label = QtWidgets.QLabel(ProfileWindow)
        self.nickname_label.setObjectName("nickname_label")
        self.infoGl.addWidget(self.nickname_label, 2, 0, 1, 1)
        self.emailLabel_2 = QtWidgets.QLabel(ProfileWindow)
        self.emailLabel_2.setText("")
        self.emailLabel_2.setObjectName("emailLabel_2")
        self.infoGl.addWidget(self.emailLabel_2, 3, 2, 1, 1)
        self.mscolabURLLabel_2 = QtWidgets.QLabel(ProfileWindow)
        self.mscolabURLLabel_2.setText("")
        self.mscolabURLLabel_2.setObjectName("mscolabURLLabel_2")
        self.infoGl.addWidget(self.mscolabURLLabel_2, 4, 2, 1, 1)
        self.usernameLabel = QtWidgets.QLabel(ProfileWindow)
        self.usernameLabel.setObjectName("usernameLabel")
        self.infoGl.addWidget(self.usernameLabel, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(ProfileWindow)
        self.label_5.setObjectName("label_5")
        self.infoGl.addWidget(self.label_5, 2, 1, 1, 1)
        self.mscolabURLLabel = QtWidgets.QLabel(ProfileWindow)
        self.mscolabURLLabel.setObjectName("mscolabURLLabel")
        self.infoGl.addWidget(self.mscolabURLLabel, 4, 0, 1, 1)
        self.nickname_label2 = QtWidgets.QLabel(ProfileWindow)
        self.nickname_label2.setText("")
        self.nickname_label2.setObjectName("nickname_label2")
        self.infoGl.addWidget(self.nickname_label2, 2, 2, 1, 1)
        self.emailLabel = QtWidgets.QLabel(ProfileWindow)
        self.emailLabel.setObjectName("emailLabel")
        self.infoGl.addWidget(self.emailLabel, 3, 0, 1, 1)
        self.fullname_label = QtWidgets.QLabel(ProfileWindow)
        self.fullname_label.setObjectName("fullname_label")
        self.infoGl.addWidget(self.fullname_label, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(ProfileWindow)
        self.label_6.setObjectName("label_6")
        self.infoGl.addWidget(self.label_6, 1, 1, 1, 1)
        self.fullname_label2 = QtWidgets.QLabel(ProfileWindow)
        self.fullname_label2.setText("")
        self.fullname_label2.setObjectName("fullname_label2")
        self.infoGl.addWidget(self.fullname_label2, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.infoGl, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ProfileWindow)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 1, QtCore.Qt.AlignRight)
        self.gravatarVl = QtWidgets.QVBoxLayout()
        self.gravatarVl.setObjectName("gravatarVl")
        self.gravatarLabel = QtWidgets.QLabel(ProfileWindow)
        self.gravatarLabel.setText("")
        self.gravatarLabel.setPixmap(QtGui.QPixmap(":/gravatars/default-gravatars/default.png"))
        self.gravatarLabel.setScaledContents(True)
        self.gravatarLabel.setObjectName("gravatarLabel")
        self.gravatarVl.addWidget(self.gravatarLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout.addLayout(self.gravatarVl, 0, 1, 2, 1)
        self.deleteAccountBtn = QtWidgets.QPushButton(ProfileWindow)
        self.deleteAccountBtn.setAutoDefault(False)
        self.deleteAccountBtn.setObjectName("deleteAccountBtn")
        self.gridLayout.addWidget(self.deleteAccountBtn, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.editNicknameBtn = QtWidgets.QPushButton(ProfileWindow)
        self.editNicknameBtn.setObjectName("editNicknameBtn")
        self.gridLayout.addWidget(self.editNicknameBtn, 3, 0, 1, 1)
        self.editFullnameBtn = QtWidgets.QPushButton(ProfileWindow)
        self.editFullnameBtn.setObjectName("editFullnameBtn")
        self.gridLayout.addWidget(self.editFullnameBtn, 3, 1, 1, 1)

        self.retranslateUi(ProfileWindow)
        QtCore.QMetaObject.connectSlotsByName(ProfileWindow)

    def retranslateUi(self, ProfileWindow):
        _translate = QtCore.QCoreApplication.translate
        ProfileWindow.setWindowTitle(_translate("ProfileWindow", "MSColab Profile"))
        self.label.setText(_translate("ProfileWindow", ":"))
        self.label_3.setText(_translate("ProfileWindow", ":"))
        self.label_2.setText(_translate("ProfileWindow", ":"))
        self.nickname_label.setText(_translate("ProfileWindow", "Nick Name"))
        self.usernameLabel.setText(_translate("ProfileWindow", "Name"))
        self.label_5.setText(_translate("ProfileWindow", ":"))
        self.mscolabURLLabel.setText(_translate("ProfileWindow", "Mscolab"))
        self.emailLabel.setText(_translate("ProfileWindow", "Email"))
        self.fullname_label.setText(_translate("ProfileWindow", "Full Name"))
        self.label_6.setText(_translate("ProfileWindow", ":"))
        self.deleteAccountBtn.setText(_translate("ProfileWindow", "Delete Account"))
        self.editNicknameBtn.setText(_translate("ProfileWindow", "Edit Nick Name"))
        self.editFullnameBtn.setText(_translate("ProfileWindow", "Edit Full Name"))

