# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mslib/msui/ui/ui_mscolab_connect_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MSColabConnectWindow(object):
    def setupUi(self, MSColabConnectWindow):
        MSColabConnectWindow.setObjectName("MSColabConnectWindow")
        MSColabConnectWindow.resize(468, 298)
        self.centralwidget = QtWidgets.QWidget(MSColabConnectWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.connectToMSColabFrame = QtWidgets.QFrame(self.centralwidget)
        self.connectToMSColabFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.connectToMSColabFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.connectToMSColabFrame.setObjectName("connectToMSColabFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.connectToMSColabFrame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.urlCb = QtWidgets.QComboBox(self.connectToMSColabFrame)
        self.urlCb.setObjectName("urlCb")
        self.gridLayout_3.addWidget(self.urlCb, 1, 1, 1, 1)
        self.urlLabel = QtWidgets.QLabel(self.connectToMSColabFrame)
        self.urlLabel.setObjectName("urlLabel")
        self.gridLayout_3.addWidget(self.urlLabel, 1, 0, 1, 1)
        self.connectBtn = QtWidgets.QPushButton(self.connectToMSColabFrame)
        self.connectBtn.setObjectName("connectBtn")
        self.gridLayout_3.addWidget(self.connectBtn, 1, 2, 1, 1)
        self.connectTopicLabel = QtWidgets.QLabel(self.connectToMSColabFrame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.connectTopicLabel.setFont(font)
        self.connectTopicLabel.setObjectName("connectTopicLabel")
        self.gridLayout_3.addWidget(self.connectTopicLabel, 0, 0, 1, 3)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.verticalLayout.addWidget(self.connectToMSColabFrame)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.loginPage)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.loginFrame = QtWidgets.QFrame(self.loginPage)
        self.loginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.loginFrame)
        self.gridLayout_4.setContentsMargins(100, 0, 100, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.loginTopicLabel = QtWidgets.QLabel(self.loginFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.loginTopicLabel.setFont(font)
        self.loginTopicLabel.setObjectName("loginTopicLabel")
        self.gridLayout_4.addWidget(self.loginTopicLabel, 0, 1, 1, 2, QtCore.Qt.AlignHCenter)
        self.loginPasswordLe = QtWidgets.QLineEdit(self.loginFrame)
        self.loginPasswordLe.setObjectName("loginPasswordLe")
        self.gridLayout_4.addWidget(self.loginPasswordLe, 2, 1, 1, 2)
        self.loginEmailLe = QtWidgets.QLineEdit(self.loginFrame)
        self.loginEmailLe.setObjectName("loginEmailLe")
        self.gridLayout_4.addWidget(self.loginEmailLe, 1, 1, 1, 2)
        self.clickNewUserLabel = QtWidgets.QLabel(self.loginFrame)
        self.clickNewUserLabel.setObjectName("clickNewUserLabel")
        self.gridLayout_4.addWidget(self.clickNewUserLabel, 4, 1, 1, 1)
        self.loginBtn = QtWidgets.QPushButton(self.loginFrame)
        self.loginBtn.setObjectName("loginBtn")
        self.gridLayout_4.addWidget(self.loginBtn, 3, 1, 1, 2)
        self.addUserBtn = QtWidgets.QPushButton(self.loginFrame)
        self.addUserBtn.setObjectName("addUserBtn")
        self.gridLayout_4.addWidget(self.addUserBtn, 4, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.loginFrame)
        self.stackedWidget.addWidget(self.loginPage)
        self.newuserPage = QtWidgets.QWidget()
        self.newuserPage.setObjectName("newuserPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.newuserPage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newUserFrame = QtWidgets.QFrame(self.newuserPage)
        self.newUserFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.newUserFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newUserFrame.setObjectName("newUserFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.newUserFrame)
        self.gridLayout_2.setContentsMargins(25, 0, 75, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.newPasswordLabel = QtWidgets.QLabel(self.newUserFrame)
        self.newPasswordLabel.setObjectName("newPasswordLabel")
        self.gridLayout_2.addWidget(self.newPasswordLabel, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.newPasswordLe = QtWidgets.QLineEdit(self.newUserFrame)
        self.newPasswordLe.setObjectName("newPasswordLe")
        self.gridLayout_2.addWidget(self.newPasswordLe, 3, 1, 1, 1)
        self.newUsernameLabel = QtWidgets.QLabel(self.newUserFrame)
        self.newUsernameLabel.setObjectName("newUsernameLabel")
        self.gridLayout_2.addWidget(self.newUsernameLabel, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.newUsernameLe = QtWidgets.QLineEdit(self.newUserFrame)
        self.newUsernameLe.setObjectName("newUsernameLe")
        self.gridLayout_2.addWidget(self.newUsernameLe, 1, 1, 1, 1)
        self.newConfirmPasswordLabel = QtWidgets.QLabel(self.newUserFrame)
        self.newConfirmPasswordLabel.setObjectName("newConfirmPasswordLabel")
        self.gridLayout_2.addWidget(self.newConfirmPasswordLabel, 4, 0, 1, 1, QtCore.Qt.AlignRight)
        self.newUserTopicLabel = QtWidgets.QLabel(self.newUserFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.newUserTopicLabel.setFont(font)
        self.newUserTopicLabel.setObjectName("newUserTopicLabel")
        self.gridLayout_2.addWidget(self.newUserTopicLabel, 0, 1, 1, 1)
        self.newEmailLe = QtWidgets.QLineEdit(self.newUserFrame)
        self.newEmailLe.setObjectName("newEmailLe")
        self.gridLayout_2.addWidget(self.newEmailLe, 2, 1, 1, 1)
        self.newConfirmPasswordLe = QtWidgets.QLineEdit(self.newUserFrame)
        self.newConfirmPasswordLe.setObjectName("newConfirmPasswordLe")
        self.gridLayout_2.addWidget(self.newConfirmPasswordLe, 4, 1, 1, 1)
        self.newEmailLabel = QtWidgets.QLabel(self.newUserFrame)
        self.newEmailLabel.setObjectName("newEmailLabel")
        self.gridLayout_2.addWidget(self.newEmailLabel, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.newUserBb = QtWidgets.QDialogButtonBox(self.newUserFrame)
        self.newUserBb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.newUserBb.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.newUserBb.setObjectName("newUserBb")
        self.gridLayout_2.addWidget(self.newUserBb, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.newUserFrame)
        self.stackedWidget.addWidget(self.newuserPage)
        self.wmsAuthPage = QtWidgets.QWidget()
        self.wmsAuthPage.setObjectName("wmsAuthPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.wmsAuthPage)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.wmsAuthFrame = QtWidgets.QFrame(self.wmsAuthPage)
        self.wmsAuthFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wmsAuthFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wmsAuthFrame.setObjectName("wmsAuthFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.wmsAuthFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.wmsUsernameLabel = QtWidgets.QLabel(self.wmsAuthFrame)
        self.wmsUsernameLabel.setObjectName("wmsUsernameLabel")
        self.gridLayout.addWidget(self.wmsUsernameLabel, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.wmsUsernameLe = QtWidgets.QLineEdit(self.wmsAuthFrame)
        self.wmsUsernameLe.setObjectName("wmsUsernameLe")
        self.gridLayout.addWidget(self.wmsUsernameLe, 2, 1, 1, 1)
        self.wmsPasswordLabel = QtWidgets.QLabel(self.wmsAuthFrame)
        self.wmsPasswordLabel.setObjectName("wmsPasswordLabel")
        self.gridLayout.addWidget(self.wmsPasswordLabel, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.wmsBb = QtWidgets.QDialogButtonBox(self.wmsAuthFrame)
        self.wmsBb.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.wmsBb.setObjectName("wmsBb")
        self.gridLayout.addWidget(self.wmsBb, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.wmsPasswordLe = QtWidgets.QLineEdit(self.wmsAuthFrame)
        self.wmsPasswordLe.setObjectName("wmsPasswordLe")
        self.gridLayout.addWidget(self.wmsPasswordLe, 3, 1, 1, 1)
        self.wmsTopicLabel = QtWidgets.QLabel(self.wmsAuthFrame)
        self.wmsTopicLabel.setObjectName("wmsTopicLabel")
        self.gridLayout.addWidget(self.wmsTopicLabel, 0, 0, 1, 2)
        self.wmsInfoLabel = QtWidgets.QLabel(self.wmsAuthFrame)
        self.wmsInfoLabel.setObjectName("wmsInfoLabel")
        self.gridLayout.addWidget(self.wmsInfoLabel, 1, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.wmsAuthFrame)
        self.stackedWidget.addWidget(self.wmsAuthPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        MSColabConnectWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MSColabConnectWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MSColabConnectWindow)
        MSColabConnectWindow.setTabOrder(self.urlCb, self.connectBtn)
        MSColabConnectWindow.setTabOrder(self.connectBtn, self.loginEmailLe)
        MSColabConnectWindow.setTabOrder(self.loginEmailLe, self.loginPasswordLe)
        MSColabConnectWindow.setTabOrder(self.loginPasswordLe, self.loginBtn)
        MSColabConnectWindow.setTabOrder(self.loginBtn, self.addUserBtn)
        MSColabConnectWindow.setTabOrder(self.addUserBtn, self.newUsernameLe)
        MSColabConnectWindow.setTabOrder(self.newUsernameLe, self.newEmailLe)
        MSColabConnectWindow.setTabOrder(self.newEmailLe, self.newPasswordLe)
        MSColabConnectWindow.setTabOrder(self.newPasswordLe, self.newConfirmPasswordLe)
        MSColabConnectWindow.setTabOrder(self.newConfirmPasswordLe, self.wmsUsernameLe)
        MSColabConnectWindow.setTabOrder(self.wmsUsernameLe, self.wmsPasswordLe)

    def retranslateUi(self, MSColabConnectWindow):
        _translate = QtCore.QCoreApplication.translate
        MSColabConnectWindow.setWindowTitle(_translate("MSColabConnectWindow", "MSColabConnectWindow"))
        self.urlLabel.setText(_translate("MSColabConnectWindow", "MSColab URL:"))
        self.connectBtn.setText(_translate("MSColabConnectWindow", "Connect"))
        self.connectTopicLabel.setText(_translate("MSColabConnectWindow", "Connect to MSColab"))
        self.loginTopicLabel.setText(_translate("MSColabConnectWindow", "Login Details:"))
        self.loginPasswordLe.setPlaceholderText(_translate("MSColabConnectWindow", "Password"))
        self.loginEmailLe.setPlaceholderText(_translate("MSColabConnectWindow", "Email ID"))
        self.clickNewUserLabel.setText(_translate("MSColabConnectWindow", "Click here if new user"))
        self.loginBtn.setText(_translate("MSColabConnectWindow", "Login"))
        self.addUserBtn.setText(_translate("MSColabConnectWindow", "Add user"))
        self.newPasswordLabel.setText(_translate("MSColabConnectWindow", "Password:"))
        self.newPasswordLe.setPlaceholderText(_translate("MSColabConnectWindow", "New Password"))
        self.newUsernameLabel.setText(_translate("MSColabConnectWindow", "Username:"))
        self.newUsernameLe.setPlaceholderText(_translate("MSColabConnectWindow", "John Doe"))
        self.newConfirmPasswordLabel.setText(_translate("MSColabConnectWindow", "Confirm Password:"))
        self.newUserTopicLabel.setText(_translate("MSColabConnectWindow", "New User Details"))
        self.newEmailLe.setPlaceholderText(_translate("MSColabConnectWindow", "johndoe@gmail.com"))
        self.newConfirmPasswordLe.setPlaceholderText(_translate("MSColabConnectWindow", "Confirm New Password"))
        self.newEmailLabel.setText(_translate("MSColabConnectWindow", "Email:"))
        self.wmsUsernameLabel.setText(_translate("MSColabConnectWindow", "Username:"))
        self.wmsUsernameLe.setPlaceholderText(_translate("MSColabConnectWindow", "Server Auth Username"))
        self.wmsPasswordLabel.setText(_translate("MSColabConnectWindow", "Password:"))
        self.wmsPasswordLe.setPlaceholderText(_translate("MSColabConnectWindow", "Server Auth Password"))
        self.wmsTopicLabel.setText(_translate("MSColabConnectWindow", "Web Map Service"))
        self.wmsInfoLabel.setText(_translate("MSColabConnectWindow", "The server you are trying to connect requires a username and a password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MSColabConnectWindow = QtWidgets.QMainWindow()
    ui = Ui_MSColabConnectWindow()
    ui.setupUi(MSColabConnectWindow)
    MSColabConnectWindow.show()
    sys.exit(app.exec_())
