# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mslib/msui/ui/ui_operation_archive.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OperationArchiveBrowser(object):
    def setupUi(self, OperationArchiveBrowser):
        OperationArchiveBrowser.setObjectName("OperationArchiveBrowser")
        OperationArchiveBrowser.resize(754, 393)
        self.verticalLayout = QtWidgets.QVBoxLayout(OperationArchiveBrowser)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(OperationArchiveBrowser)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listArchivedOperations = QtWidgets.QListWidget(OperationArchiveBrowser)
        self.listArchivedOperations.setObjectName("listArchivedOperations")
        self.verticalLayout.addWidget(self.listArchivedOperations)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbUnarchiveOperation = QtWidgets.QPushButton(OperationArchiveBrowser)
        self.pbUnarchiveOperation.setObjectName("pbUnarchiveOperation")
        self.horizontalLayout.addWidget(self.pbUnarchiveOperation)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pbClose = QtWidgets.QPushButton(OperationArchiveBrowser)
        self.pbClose.setObjectName("pbClose")
        self.horizontalLayout.addWidget(self.pbClose)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(OperationArchiveBrowser)
        QtCore.QMetaObject.connectSlotsByName(OperationArchiveBrowser)

    def retranslateUi(self, OperationArchiveBrowser):
        _translate = QtCore.QCoreApplication.translate
        OperationArchiveBrowser.setWindowTitle(_translate("OperationArchiveBrowser", "Browse archived operations"))
        self.label.setText(_translate("OperationArchiveBrowser", "Operation Archive"))
        self.pbUnarchiveOperation.setToolTip(_translate("OperationArchiveBrowser", "<html><head/><body><p>Becomes available when you have the right to unarchive an operation. Moves this operation to the list of current operations.</p></body></html>"))
        self.pbUnarchiveOperation.setText(_translate("OperationArchiveBrowser", "Unarchive"))
        self.pbClose.setText(_translate("OperationArchiveBrowser", "close"))
