# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_topview_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TopViewWindow(object):
    def setupUi(self, TopViewWindow):
        TopViewWindow.setObjectName("TopViewWindow")
        TopViewWindow.resize(952, 782)
        self.centralwidget = QtWidgets.QWidget(TopViewWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mpl = MplTopViewWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setMinimumSize(QtCore.QSize(100, 100))
        self.mpl.setObjectName("mpl")
        self.horizontalLayout_2.addWidget(self.mpl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btMapRedraw = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btMapRedraw.setFont(font)
        self.btMapRedraw.setFlat(False)
        self.btMapRedraw.setObjectName("btMapRedraw")
        self.horizontalLayout.addWidget(self.btMapRedraw)
        self.btSettings = QtWidgets.QPushButton(self.centralwidget)
        self.btSettings.setObjectName("btSettings")
        self.horizontalLayout.addWidget(self.btSettings)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cbTools = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTools.sizePolicy().hasHeightForWidth())
        self.cbTools.setSizePolicy(sizePolicy)
        self.cbTools.setObjectName("cbTools")
        self.cbTools.addItem("")
        self.cbTools.addItem("")
        self.horizontalLayout.addWidget(self.cbTools)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cbChangeMapSection = QtWidgets.QComboBox(self.centralwidget)
        self.cbChangeMapSection.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cbChangeMapSection.setObjectName("cbChangeMapSection")
        self.cbChangeMapSection.addItem("")
        self.cbChangeMapSection.addItem("")
        self.cbChangeMapSection.addItem("")
        self.cbChangeMapSection.addItem("")
        self.cbChangeMapSection.addItem("")
        self.cbChangeMapSection.addItem("")
        self.cbChangeMapSection.addItem("")
        self.horizontalLayout.addWidget(self.cbChangeMapSection)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.btMvWaypoint = QtWidgets.QToolButton(self.centralwidget)
        self.btMvWaypoint.setCheckable(True)
        self.btMvWaypoint.setChecked(True)
        self.btMvWaypoint.setAutoExclusive(True)
        self.btMvWaypoint.setObjectName("btMvWaypoint")
        self.horizontalLayout.addWidget(self.btMvWaypoint)
        self.btInsWaypoint = QtWidgets.QToolButton(self.centralwidget)
        self.btInsWaypoint.setCheckable(True)
        self.btInsWaypoint.setAutoExclusive(True)
        self.btInsWaypoint.setObjectName("btInsWaypoint")
        self.horizontalLayout.addWidget(self.btInsWaypoint)
        self.btDelWaypoint = QtWidgets.QToolButton(self.centralwidget)
        self.btDelWaypoint.setCheckable(True)
        self.btDelWaypoint.setAutoExclusive(True)
        self.btDelWaypoint.setObjectName("btDelWaypoint")
        self.horizontalLayout.addWidget(self.btDelWaypoint)
        self.verticalLayout.addLayout(self.horizontalLayout)
        TopViewWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TopViewWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 26))
        self.menubar.setObjectName("menubar")
        TopViewWindow.setMenuBar(self.menubar)

        self.retranslateUi(TopViewWindow)
        QtCore.QMetaObject.connectSlotsByName(TopViewWindow)

    def retranslateUi(self, TopViewWindow):
        _translate = QtCore.QCoreApplication.translate
        TopViewWindow.setWindowTitle(_translate("TopViewWindow", "Top View - Mission Support System"))
        self.btMapRedraw.setText(_translate("TopViewWindow", "&REDRAW MAP"))
        self.btMapRedraw.setShortcut(_translate("TopViewWindow", "R"))
        self.btSettings.setText(_translate("TopViewWindow", "map appearance"))
        self.cbTools.setItemText(0, _translate("TopViewWindow", "(select to open tool)"))
        self.cbTools.setItemText(1, _translate("TopViewWindow", "WMS"))
        self.cbChangeMapSection.setItemText(0, _translate("TopViewWindow", "to reset map select a region"))
        self.cbChangeMapSection.setItemText(1, _translate("TopViewWindow", "Spitsbergen, large"))
        self.cbChangeMapSection.setItemText(2, _translate("TopViewWindow", "Spitsbergen, local"))
        self.cbChangeMapSection.setItemText(3, _translate("TopViewWindow", "Europe (ste)"))
        self.cbChangeMapSection.setItemText(4, _translate("TopViewWindow", "Germany (ste)"))
        self.cbChangeMapSection.setItemText(5, _translate("TopViewWindow", "Europe (cyl)"))
        self.cbChangeMapSection.setItemText(6, _translate("TopViewWindow", "Germany (cyl)"))
        self.label.setText(_translate("TopViewWindow", "waypoint edit mode:"))
        self.btMvWaypoint.setText(_translate("TopViewWindow", "&Mv"))
        self.btMvWaypoint.setShortcut(_translate("TopViewWindow", "M"))
        self.btInsWaypoint.setText(_translate("TopViewWindow", "&Ins"))
        self.btInsWaypoint.setShortcut(_translate("TopViewWindow", "I"))
        self.btDelWaypoint.setText(_translate("TopViewWindow", "&Del"))
        self.btDelWaypoint.setShortcut(_translate("TopViewWindow", "D"))

from mslib.msui.mpl_qtwidget import MplTopViewWidget
