# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Loginwms(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(515, 248)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 39, 311, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.userNameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.userNameLabel.setObjectName("userNameLabel")
        self.horizontalLayout.addWidget(self.userNameLabel)
        self.userNameLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.horizontalLayout.addWidget(self.userNameLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.passwordLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.horizontalLayout_2.addWidget(self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.horizontalLayout_2.addWidget(self.passwordLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.savePushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.savePushButton.setObjectName("savePushButton")
        self.verticalLayout.addWidget(self.savePushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "HTTP Authentication"))
        self.userNameLabel.setText(_translate("Form", "         Username:          "))
        self.passwordLabel.setText(_translate("Form", "         Password:           "))
        self.savePushButton.setText(_translate("Form", "Save"))
