{% set version = "alpha" %}


package:
  name: mss
  version: {{ version }}

source:
  path: ../

build:
  skip: true  # [py<38]
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"  # [not win]
  entry_points:
    - msui = mslib.msui.msui:main
    - mss = mslib.msui.mss:main
    - mswms = mslib.mswms.mswms:main
    - mswms_demodata = mslib.mswms.demodata:main
    - mscolab = mslib.mscolab.mscolab:main
    - mssautoplot = mslib.utils.mssautoplot:main

requirements:
  build:
    - python
    - pip
    - setuptools
  host:
    - python
    - setuptools
    - pip
    - future
    - menuinst  # [win]
  run:
    - python
    - defusedxml
    - menuinst  # [win]
    - basemap >=1.3.3
    - chameleon
    - execnet
    - fastkml =0.11
    - shapely <2.0.0
    - pygeoif <1.0.0
    - isodate
    - lxml
    - netcdf4
    - hdf4
    - pillow
    - pytz
    - pyqt >=5, <5.13
    - qt >=5.10, <5.13
    - requests
    - scipy
    - skyfield >=1.12
    - skyfield-data >=5
    - tk
    - owslib >=0.24
    - unicodecsv
    - fs_filepicker
    - cftime >=1.0.1
    - matplotlib >=3.3.2,<3.6
    - itsdangerous
    - pyjwt
    - flask >=2.3.2
    - flask-httpauth
    - flask-mail
    - flask-migrate
    - werkzeug >=2.2.3
    - flask-socketio =5.1.0
    - flask-sqlalchemy >=3.0.0
    - flask-cors
    - passlib
    - gitpython
    - git
    - psycopg2
    - PyMySQL >=0.9.3
    - validate_email
    - multidict
    - pint
    - python-socketio >=5
    - python-engineio >=4
    - markdown
    - xstatic
    - xstatic-jquery
    - xstatic-bootstrap
    - gpxpy >=1.4.2
    - metpy
    - pycountry
    - websocket-client
    - libtiff <4.5.0
    - flask-wtf
    - email_validator
    - keyring
    - dbus-python

test:
  imports:
    - mslib
  commands:
    - mswms -h
    - mswms_demodata -h
    - msui -h
    - mscolab -h

about:
  summary: 'A web service based tool to plan atmospheric research flights.'
  home: https://github.com/Open-MSS/MSS
  license: "Apache-2.0"
  license_family: "APACHE"
  license_file: LICENSE
  description: |
    MSS - Mission Support System

    http://www.geosci-model-dev.net/5/55/2012/gmd-5-55-2012.pdf

    Software for planning research Aircraft Missions.
    For discussion of the possibilites of the research flights,
    the Mission Support System (MSS) was developed.
    This software helps to review a big amount of metereological and
    model data by viewing the forecasted parameters of interest along possible regions
    of a proposed flight path. Data and possible flight paths can
    be displayed on a hoizontal view (map projection) or on a vertical
    view (along the proposed flight path). Flight paths can be constructed
    and modified on these views. Exchange through a waypoint table is also possible.

extra:
  recipe-maintainers:
    - ReimarBauer
