name: rtd
channels:
  - conda-forge
dependencies:
  - python =3.11
  - pip
  - pip:
      - flask
      - flask-httpauth
      - chameleon
      - multidict
      - isodate
      - scipy
      - metpy
      - markdown
      - xstatic>=1.0.3
      - xstatic-jquery
      - xstatic-bootstrap
      - defusedxml
      - sphinx_rtd_theme
      - sphinxcontrib-video>=0.2.1
      - sphinx
      - fs
      - netCDF4
      - PyQt5
      - owslib
  - basemap >=1.3.3
  - pint
