# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_loopwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!


from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ImageLoopWindow(object):
    def setupUi(self, ImageLoopWindow):
        ImageLoopWindow.setObjectName(_fromUtf8("ImageLoopWindow"))
        ImageLoopWindow.resize(1042, 717)
        ImageLoopWindow.setStatusTip(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(ImageLoopWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.dteValidTime = QtGui.QDateTimeEdit(self.centralwidget)
        self.dteValidTime.setMinimumSize(QtCore.QSize(220, 0))
        self.dteValidTime.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.dteValidTime.setFont(font)
        self.dteValidTime.setReadOnly(True)
        self.dteValidTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dteValidTime.setDate(QtCore.QDate(2010, 1, 22))
        self.dteValidTime.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(12, 0, 0)))
        self.dteValidTime.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.dteValidTime.setMinimumTime(QtCore.QTime(12, 0, 0))
        self.dteValidTime.setCalendarPopup(False)
        self.dteValidTime.setTimeSpec(QtCore.Qt.UTC)
        self.dteValidTime.setObjectName(_fromUtf8("dteValidTime"))
        self.horizontalLayout_3.addWidget(self.dteValidTime)
        self.tbValidTime_back = QtGui.QToolButton(self.centralwidget)
        self.tbValidTime_back.setArrowType(QtCore.Qt.LeftArrow)
        self.tbValidTime_back.setObjectName(_fromUtf8("tbValidTime_back"))
        self.horizontalLayout_3.addWidget(self.tbValidTime_back)
        self.cbVTStep = QtGui.QComboBox(self.centralwidget)
        self.cbVTStep.setObjectName(_fromUtf8("cbVTStep"))
        self.cbVTStep.addItem(_fromUtf8(""))
        self.cbVTStep.addItem(_fromUtf8(""))
        self.cbVTStep.addItem(_fromUtf8(""))
        self.cbVTStep.addItem(_fromUtf8(""))
        self.cbVTStep.addItem(_fromUtf8(""))
        self.cbVTStep.addItem(_fromUtf8(""))
        self.cbVTStep.addItem(_fromUtf8(""))
        self.cbVTStep.addItem(_fromUtf8(""))
        self.cbVTStep.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cbVTStep)
        self.tbValidTime_fwd = QtGui.QToolButton(self.centralwidget)
        self.tbValidTime_fwd.setArrowType(QtCore.Qt.RightArrow)
        self.tbValidTime_fwd.setObjectName(_fromUtf8("tbValidTime_fwd"))
        self.horizontalLayout_3.addWidget(self.tbValidTime_fwd)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.centralFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralFrame.sizePolicy().hasHeightForWidth())
        self.centralFrame.setSizePolicy(sizePolicy)
        self.centralFrame.setFrameShape(QtGui.QFrame.Box)
        self.centralFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.centralFrame.setObjectName(_fromUtf8("centralFrame"))
        self.verticalLayout.addWidget(self.centralFrame)
        ImageLoopWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ImageLoopWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Layout = QtGui.QMenu(self.menubar)
        self.menu_Layout.setObjectName(_fromUtf8("menu_Layout"))
        ImageLoopWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(ImageLoopWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        ImageLoopWindow.setStatusBar(self.statusBar)
        self.actionE_xit = QtGui.QAction(ImageLoopWindow)
        self.actionE_xit.setObjectName(_fromUtf8("actionE_xit"))
        self.actionSingleView = QtGui.QAction(ImageLoopWindow)
        self.actionSingleView.setObjectName(_fromUtf8("actionSingleView"))
        self.actionDualView = QtGui.QAction(ImageLoopWindow)
        self.actionDualView.setObjectName(_fromUtf8("actionDualView"))
        self.actionOneLargeTwoSmall = QtGui.QAction(ImageLoopWindow)
        self.actionOneLargeTwoSmall.setObjectName(_fromUtf8("actionOneLargeTwoSmall"))
        self.actionOneLargeThreeSmall = QtGui.QAction(ImageLoopWindow)
        self.actionOneLargeThreeSmall.setObjectName(_fromUtf8("actionOneLargeThreeSmall"))
        self.actionQuadView = QtGui.QAction(ImageLoopWindow)
        self.actionQuadView.setObjectName(_fromUtf8("actionQuadView"))
        self.menu_File.addAction(self.actionE_xit)
        self.menu_Layout.addAction(self.actionSingleView)
        self.menu_Layout.addAction(self.actionDualView)
        self.menu_Layout.addAction(self.actionOneLargeTwoSmall)
        self.menu_Layout.addAction(self.actionOneLargeThreeSmall)
        self.menu_Layout.addAction(self.actionQuadView)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Layout.menuAction())

        self.retranslateUi(ImageLoopWindow)
        QtCore.QObject.connect(self.actionE_xit, QtCore.SIGNAL(_fromUtf8("triggered()")), ImageLoopWindow.close)
        QtCore.QMetaObject.connectSlotsByName(ImageLoopWindow)

    def retranslateUi(self, ImageLoopWindow):
        ImageLoopWindow.setWindowTitle(_translate("ImageLoopWindow", "Loop View - Mission Support System", None))
        self.label_3.setText(_translate("ImageLoopWindow", "Synchronized Valid Time:", None))
        self.dteValidTime.setDisplayFormat(_translate("ImageLoopWindow", "yyyy-MM-dd hh:mm UTC", None))
        self.tbValidTime_back.setToolTip(_translate("ImageLoopWindow", "decrement time", None))
        self.tbValidTime_back.setText(_translate("ImageLoopWindow", "<<", None))
        self.cbVTStep.setToolTip(_translate("ImageLoopWindow", "time step for changing the valid time", None))
        self.cbVTStep.setItemText(0, _translate("ImageLoopWindow", "5 min", None))
        self.cbVTStep.setItemText(1, _translate("ImageLoopWindow", "10 min", None))
        self.cbVTStep.setItemText(2, _translate("ImageLoopWindow", "15 min", None))
        self.cbVTStep.setItemText(3, _translate("ImageLoopWindow", "30 min", None))
        self.cbVTStep.setItemText(4, _translate("ImageLoopWindow", "1 hour", None))
        self.cbVTStep.setItemText(5, _translate("ImageLoopWindow", "3 hours", None))
        self.cbVTStep.setItemText(6, _translate("ImageLoopWindow", "6 hours", None))
        self.cbVTStep.setItemText(7, _translate("ImageLoopWindow", "12 hours", None))
        self.cbVTStep.setItemText(8, _translate("ImageLoopWindow", "24 hours", None))
        self.tbValidTime_fwd.setToolTip(_translate("ImageLoopWindow", "increment time", None))
        self.tbValidTime_fwd.setText(_translate("ImageLoopWindow", ">>", None))
        self.menu_File.setTitle(_translate("ImageLoopWindow", "&File", None))
        self.menu_Layout.setTitle(_translate("ImageLoopWindow", "&Layout", None))
        self.actionE_xit.setText(_translate("ImageLoopWindow", "E&xit Module", None))
        self.actionE_xit.setShortcut(_translate("ImageLoopWindow", "Ctrl+X", None))
        self.actionSingleView.setText(_translate("ImageLoopWindow", "&Single View", None))
        self.actionSingleView.setShortcut(_translate("ImageLoopWindow", "Alt+1", None))
        self.actionDualView.setText(_translate("ImageLoopWindow", "&Dual View", None))
        self.actionDualView.setShortcut(_translate("ImageLoopWindow", "Alt+2", None))
        self.actionOneLargeTwoSmall.setText(_translate("ImageLoopWindow", "&One Large, Two Small", None))
        self.actionOneLargeTwoSmall.setShortcut(_translate("ImageLoopWindow", "Alt+3", None))
        self.actionOneLargeThreeSmall.setText(_translate("ImageLoopWindow", "One &Large, Three Small", None))
        self.actionOneLargeThreeSmall.setShortcut(_translate("ImageLoopWindow", "Alt+4", None))
        self.actionQuadView.setText(_translate("ImageLoopWindow", "&Quad View", None))
        self.actionQuadView.setShortcut(_translate("ImageLoopWindow", "Alt+5", None))

