name: Build Gallery

on:
   pull_request:

jobs:
  Test-MSS-docs:
    runs-on: ubuntu-latest

    container:
      image: openmss/testing-develop

    steps:
    - uses: actions/checkout@v4

    - name: Create gallery
      timeout-minutes: 5
      run: |
        cd docs
        mamba run --no-capture-output -n mssenv python conf.py
