name: Build Gallery

on: 
   pull_request:
     inputs:
        branch_name:
          required: true
          type: string
        secrets:
          PAT:
            required: true

env:
  PAT: ${{ secrets.PAT }}
  EVENT: ${{ inputs.event_name }}

jobs:
  Test-MSS-docs:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    container:
      image: openmss/testing-${{ inputs.branch_name }}

    steps:
    - name: Trust My Directory
      run: git config --global --add safe.directory /__w/MSS/MSS
    - uses: actions/checkout@v3

    - name: Create gallery
      timeout-minutes: 25
      run: |
        source /opt/conda/bin/activate mssenv \
        && cd $GITHUB_WORKSPACE/docs \
        && python conf.py
