name: Build Gallery

on:
  pull_request:

jobs:
  Test-MSS-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: prefix-dev/setup-pixi@5044b250243a57e8c78f7c38acd73f6d7954a3cf # v0.8.7
      with:
        pixi-version: latest
        cache: true
        environments: dev
    - name: Create gallery
      timeout-minutes: 5
      run: |
        cd docs
        pixi run -e dev python conf.py
