name: Build Gallery

on:
  pull_request:

jobs:
  Test-MSS-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: prefix-dev/setup-pixi@8ca4608ef7f4daeb54f5205b20d0b7cb42f11143 # v0.8.14
      with:
        pixi-version: latest
        cache: true
        environments: dev
    - name: Create gallery
      timeout-minutes: 5
      run: |
        cd docs
        pixi run -e dev python conf.py
