name: Build Gallery

on:
  pull_request:

jobs:
  Test-MSS-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
    - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
      with:
        pixi-version: latest
        cache: true
        environments: dev
    - name: Create gallery
      timeout-minutes: 5
      run: |
        cd docs
        pixi run -e dev python conf.py
