name: Build Gallery

on:
  pull_request:

jobs:
  Test-MSS-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.5.1
      with:
        pixi-version: latest
        cache: true
        environments: dev
    - name: Create gallery
      timeout-minutes: 5
      run: |
        cd docs
        pixi run -e dev python conf.py
