name: Build Gallery

on: pull_request

jobs:
  Test-MSS-docs:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    container:
      image: openmss/mss-test:latest

    steps:
    - name: Trust My Directory
      run: git config --global --add safe.directory /__w/MSS/MSS
    - uses: actions/checkout@v2

    - name: creste docs
      timeout-minutes: 25
      run: |
        source /opt/conda/bin/activate mssenv \
        && cd $GITHUB_WORKSPACE/docs \
        && python conf.py
