on:
  push:
    branches:
    - develop
    - stable
    - 'GSOC**'
  pull_request:

name: Security

jobs:
  ensure-pinned-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@4830be28ce81da52ec70d65c552a7403821d98d4 # v3
        with:
          allowlist: |
            Open-MSS/
          dry_run: 'false'

jobs:
  frizbee_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: stacklok/frizbee-action@a0f3391cbe93a54e2a68cfaca2283f8cf3fd72ea # v0.0.2
        with:
          actions: .github/workflows
          open_pr: true
          fail_on_unpinned: true
          token: ${{ secrets.PAT }}
          branch: automation/update-sha
          add-paths:
            - build_docs_gallery.yml
            - lint.yml
            - testing-all-oses.yml
            - update-pixi-lockfile.yml
          delete-branch: true
          commit-message: Update sha of actions
          title: Update sha of actions
          body-path: diff.md
