name: lint

on:
  push:
    branches:
    - develop
    - stable
  pull_request:
    branches:
    - develop
    - stable

jobs:
  flake8:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        flake8 --count --statistics mslib tests
