name: lint

on:
  push:
    branches:
    - develop
    - stable
  pull_request:
    branches:
    - develop
    - stable

jobs:
  flake8:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        flake8 --count --statistics mslib tests

  no-crlf-in-git:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Check for CRLF in the repository
      run: |
        files_with_crlf="$(git ls-files --eol | awk '$1 ~ "crlf"')"
        echo "$files_with_crlf"
        [ "$files_with_crlf" == "" ] || exit 1

  no-whitespace-issues-in-git:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Check for whitespace issues in the repository
      run: git diff --check $(git hash-object -t tree /dev/null) HEAD
