name: RTFD env basics

on:
  pull_request:

jobs:
  Test-RTFD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
    - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
      with:
        pixi-version: latest
        cache: true
        environments: docs
    - name: try sphinx build
      timeout-minutes: 20
      run: |
        pixi run -e docs sphinx-build -T -b html docs docs/html
