name: RTFD env basics

on:
  pull_request:

jobs:
  Test-RTFD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
    - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
      with:
        pixi-version: latest
        cache: true
        environments: docs
    - name: try sphinx build
      timeout-minutes: 20
      run: |
        pixi run -e docs sphinx-build -T -b html docs docs/html
