name: test GSoC

on:
  push:
    branches:
    - 'GSOC**'
  pull_request:
    branches:
    - 'GSOC**'

jobs:
  test-gsoc:
    uses:
      ./.github/workflows/testing.yml
    with:
      image_suffix: develop
