name: Test MSS

on:
  push:
    branches:
      - develop
      - stable
      - 'GSOC**'
  pull_request:
    branches:
      - develop
      - stable
      - 'GSOC**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-13", "macos-14", "ubuntu-latest"]
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
    - uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7 # v0.9.3
      with:
        pixi-version: latest
        cache: true
        environments: dev
    - name: Run tests
      timeout-minutes: 40
      run: pixi run -e dev env QT_QPA_PLATFORM=offscreen pytest -v -n logical --durations=20 --cov=mslib tests
    - run: pixi run -e dev coverage xml
    - name: Send coverage to Coveralls (parallel)
      uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
      with:
        debug: true
        parallel: true
        format: cobertura
        flag-name: ${{ join(matrix.*, ' - ') }}

  finish:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
        with:
          parallel-finished: true
