name: new dependency test (scheduled)

on:
  schedule:
    - cron: '30 5 * * 1'

jobs:
  trigger-testing-stable:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: benc-uk/workflow-dispatch@v1.2.4
        with:
          workflow: testing-stable.yml
          ref: stable

  trigger-testing-develop:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: benc-uk/workflow-dispatch@v1.2.4
        with:
          workflow: testing-develop.yml
          ref: develop
