name: Test MSS

on:
  push:
    branches:
      - develop
      - stable
      - 'GSOC**'
  pull_request:
    branches:
      - develop
      - stable
      - 'GSOC**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-14", "macos-15", "macos-26", "ubuntu-latest", "ubuntu-24.04-arm"]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
    - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
      with:
        pixi-version: latest
        cache: true
        environments: dev
    - name: Run tests
      timeout-minutes: 40
      run: pixi run -e dev env QT_QPA_PLATFORM=offscreen pytest -v -n logical --durations=20 --cov=mslib tests
    - run: pixi run -e dev coverage xml
    - name: Send coverage to Coveralls (parallel)
      uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
      with:
        fail-on-error: false
        debug: true
        parallel: true
        format: cobertura
        flag-name: ${{ join(matrix.*, ' - ') }}

  finish:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
        with:
          fail-on-error: false
          parallel-finished: true
