name: new dependency test (scheduled)

on:
  schedule:
    - cron: '30 5 * * 1' 


jobs:
  trigger-testing-stable:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: testing-stable.yml
          ref: stable

  test-develop-scheduled:
    uses: 
      ./.github/workflows/testing.yml
    with:
      xdist: no
      branch_name: develop
      event_name: ${{ github.event_name }}
    secrets:
      PAT: ${{ secrets.PAT }}



