name: Test MSS

on:
  push:
    branches:
      - develop
      - stable
      - 'GSOC**'
  pull_request:
    branches:
      - develop
      - stable
      - 'GSOC**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-14", "macos-15", "ubuntu-latest"]
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
    - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
      with:
        pixi-version: latest
        cache: true
        environments: dev
    - name: Run tests
      timeout-minutes: 40
      run: pixi run -e dev env QT_QPA_PLATFORM=offscreen pytest -v -n logical --durations=20 --cov=mslib tests
    - run: pixi run -e dev coverage xml
    - name: Send coverage to Coveralls (parallel)
      uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
      with:
        fail-on-error: false
        debug: true
        parallel: true
        format: cobertura
        flag-name: ${{ join(matrix.*, ' - ') }}

  finish:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          fail-on-error: false
          parallel-finished: true
