name: test stable

on:
  push:
    branches:
    - stable
  pull_request:
    branches:
    - stable
  workflow_dispatch:

jobs:
  test-stable:
    uses:
      ./.github/workflows/testing.yml
    with:
      image_suffix: stable
    secrets:
      PAT: ${{ secrets.PAT }}
