name: Test MSS

on:
  push:
    branches:
      - develop
      - stable
      - 'GSOC**'
  pull_request:
    branches:
      - develop
      - stable
      - 'GSOC**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-13", "macos-14", "ubuntu-latest"]
        order: ["normal", "reverse"]
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.5.1
      with:
        pixi-version: latest
        cache: true
        environments: dev
    - name: Run tests
      timeout-minutes: 20
      # The ignored files can somehow cause the test suite to timeout.
      # I have no idea yet on why this happens and how to fix it.
      # Even a module level skip is not enough, they need to be completely ignored.
      # TODO: fix those tests and drop the ignores
      run: pixi run -e dev env QT_QPA_PLATFORM=offscreen pytest -v -n logical --durations=20 --cov=mslib
        --ignore=tests/_test_msui/test_sideview.py --ignore=tests/_test_msui/test_topview.py --ignore=tests/_test_msui/test_wms_control.py
        ${{ (matrix.order == 'normal' && ' ') || (matrix.order == 'reverse' && '--reverse') }} tests
