name: test stable

on:
  push:
    branches:
    - stable
  pull_request:
    branches:
    - stable
  workflow_dispatch:

jobs:
  test-stable:
    uses:
      ./.github/workflows/testing.yml
    with:
      branch_name: stable
      event_name: ${{ github.event_name }}
    secrets:
      PAT: ${{ secrets.PAT }}
