name: test stable (scheduled)

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 1' 


jobs:     
  test-stable-scheduled:
    uses: 
      ./.github/workflows/testing.yml
    with:
      xdist: no
      branch_name: stable
      event_name: ${{ github.event_name }}
    secrets:
      PAT: ${{ secrets.PAT }}

  test-develop-scheduled:
    uses: 
      ./.github/workflows/testing.yml
    with:
      xdist: no
      branch_name: develop
      event_name: ${{ github.event_name }}
    secrets:
      PAT: ${{ secrets.PAT }}



