name: test develop

on:
  push:
    branches:
    - develop
    - temp1

  pull_request:
    branches:
    - develop

jobs:
  test-develop:
    uses:
      ./.github/workflows/testing.yml
    with:
      branch_name: develop
      event_name: ${{ github.event_name }}
    secrets:
      PAT: ${{ secrets.PAT }}
