name: test stable

on:
  push:
    branches:
    - stable
  pull_request:
    branches:
    - stable

jobs:     
  test-develop:
    uses: 
      ./.github/workflows/testing.yml
    with:
      xdist: no
      branch_name: stable
      event_name: ${{ github.event_name }}
    secrets: inherit

  test-develop-xdist:
    uses: 
      ./.github/workflows/testing.yml
    with:
      xdist: yes
      branch_name: stable
      event_name: ${{ github.event_name }}
    secrets: inherit


