name: Update pixi lockfile

on:
  schedule:
  # At 04:00 on Monday
    - cron: "0 4 * * 1"
  # ...or manually
  workflow_dispatch:

jobs:
  pixi-update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base_branch: ["develop", "stable"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
        with:
          ref: ${{ matrix.base_branch }}
      - name: Generate new lockfile
        uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347 # v0.10.1
        with:
          pixi-version: latest
          run-install: false
      - name: Update pixi lockfile
        run: |
          set -o pipefail
          pixi update --json | pixi exec pixi-diff-to-markdown >> diff.md
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v7
        with:
          token: ${{ secrets.PAT }}
          branch: automation/update-pixi-lockfile/${{ matrix.base_branch }}
          delete-branch: true
          add-paths: pixi.lock
          commit-message: Update pixi lockfile
          title: Update pixi lockfile
          body-path: diff.md
