name: Update pixi lockfile

on:
  schedule:
  # At 04:00 on Monday
    - cron: "0 4 * * 1"
  # ...or manually
  workflow_dispatch:

jobs:
  update-pixi-lockfile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base_branch: ["develop", "stable"]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.base_branch }}
      - name: Remove old lockfile
        run: rm pixi.lock
      - name: Generate new lockfile
        uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: latest
          cache: false
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: pixi.lock
          branch: automation/update-pixi-lockfile
          commit-message: Update pixi lockfile
          title: Update pixi lockfile
          body: ""
