name: Update pixi lockfile

on:
  schedule:
  # At 04:00 on Monday
    - cron: "0 4 * * 1"
  # ...or manually
  workflow_dispatch:

jobs:
  pixi-update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base_branch: ["develop", "stable"]
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
        with:
          ref: ${{ matrix.base_branch }}
      - name: Generate new lockfile
        uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7 # v0.9.3
        with:
          pixi-version: latest
          run-install: false
      - name: Update pixi lockfile
        run: |
          set -o pipefail
          pixi update --json | pixi exec pixi-diff-to-markdown >> diff.md
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
        with:
          token: ${{ secrets.PAT }}
          branch: automation/update-pixi-lockfile
          delete-branch: true
          add-paths: pixi.lock
          commit-message: Update pixi lockfile
          title: Update pixi lockfile
          body-path: diff.md
